### ISSUE TITLE
Public documentation for data model

### ISSUE THREAD

**Issue by tnavatar** [tnavatar/clingen-data-model#10]
http://clingen-data-model.github.io

Sorry, was having some trouble getting this up and running before the call. It doesn't look like much now (if you've been running middleman server you'll have seen this already). I'll be improving this into something that looks much more like a finished product soon.

**Comment by srynobio** [comment]
Looks nice!

**Comment by cbizon** [comment]
Is there a way to make the page rebuild when I push docs?

**Comment by srynobio** [comment]
With github you have to manage the .io web pages on a separate branch, so changes are not made in real time with each push.

**Comment by tnavatar** [comment]
Were you ever able to get Middleman running on your computer?

**Comment by cbizon** [comment]
I never did, but I also haven't had a chance to work on it...

**Comment by tnavatar** [comment]
Let me know if I can lend a hand. It's probably the easiest way for you to see your changes in realtime.

**Comment by cbizon** [comment]
Got it - had to install the javascript interpreter outside of gem for some reason....
