### ISSUE TITLE
Integrate the model documentation with the ClinGen Website

### ISSUE THREAD

**Issue by larrybabb** [tnavatar/clingen-data-model#103]
We should get this site integrated with the www.clinicalgenome.org website before the upcoming DECIPHER/ClinGen meeting so that we can easily reference it and increase the exposure of this work.  We should do a little planning around this task with the goals of 1) keeping it simple while maintaining quality and expectations, 2) provide the ability for users of the site to submit feedback, issues or comments,  3) establish a reliable protocol and means for responding to comments in a reasonable timeframe.  

We could push the site without a feedback mechanism at first, but it would be preferrable to enable comments (I suppose a page that provides simple 1-2-3 step instructions for commenting at our github site may be the simplest, but we should consider the type of users and how to make it "easy" for them to comment.)

**Comment by tnavatar** [comment]
I've merged the new template with master and given the clingen-data-model.github.org site the subdomain datamodel.clinicalgenome.org.

More work to do (not least the link from the main site), but we're getting there.
