### ISSUE TITLE
FHIR Provenance and W3C-PROV

### ISSUE THREAD

**Issue by cbizon** [tnavatar/clingen-data-model#107]
On a recent call, I was complaining that I found FHIR Provenance to be less expressive than W3C-PROV.   This is to try to walk through some of that.  The best place to look is here:

http://www.hl7.org/FHIR/provenance.html

The little blobby picture on that page is a representation of (part) of W3C-PROV, and the blue boxes are of course FHIR.  

Note that on this page, there is a mappings tab, and in section 6.6.7.1, mappings to W3C PROV are discussed.  In that discussion is the statement: "All the parts of the resource are formally mapped to the PROV-O specification, and FHIR resources can be transformed to their W3C PROV equivalent".  However, in the following table, which is meant to be the mapping between FHIR and W3C, many of the FHIR elements do not have a mapping listed.   I interpret this as meaning that while FHIR wants its provenance elements to transform to W3C, they have not yet created a provenance where that is true.

Further, note that the mapping does not imply the opposite: That W3C PROV can be fully mapped into FHIR Provenance elements.  In fact, they can not be.   I have found, in the course of writing some PROV examples three cases that cannot (easily) be incorporated into FHIR:

1) actedOnBehalfOf: this is a relationship between two agents.  In my SimpleAllele Provenance, I used this to say that an automated process ( usually modeled as an agent) acted on behalf of a person (another agent).  Note that in the FHIR resources, there is no attribute that connects multiple agents.

2) wasStartedBy: This is a relationship between two activities.  One of the simple allele provenances was meant to model a simple allele that was created when a different simple allele was being canonicalized (like the way ClinVar creates many HGVS expressions from one).  Suppose that canonicalization (an activity) was kicked off by a bulk load (another activity).   W3C PROV represents this by an attribute connecting the two activities.   FHIR does not.   Part of the problem here, I think, is that FHIR smushes together the activity and a provenance resource, whereas W3C PROV keeps those separate, so that a particular provenance resource can naturally have more than one activity.

3) wasInvalidatedBy: This is a relationship between an entity and an activity, and it sort of  like wasGeneratedBy, except it defines when the target entity was removed.   For instance, when we generate a new version of a canonical allele, we need to set the old one to be not valid any more. W3C PROV provides an attribute between an entity and an activity explicitly saying "this activity closed that entity".  I don't see that FHIR does this.  The mapping to W3C PROV does not include this activity, and the Provenance.target is identified with W3C PROV wasGeneratedBy.

Also, following on from #3, I do not see how to specify a type to the activity, which has been rolled into the Provenance resource.  It's not any of the attributes as far as I can tell.

Sorry for the long post, but I wanted to lay out the issues as clearly as I could.  There may be other issues as well, but these are the ones that I ran into when attempting to come up with PROV examples.

**Comment by larrybabb** [comment]
Great stuff, details are useful. I will put it on my list to convey this to the fhir folks. Unless you want to do it yourself. Let me know.

**Comment by larrybabb** [comment]
Added Chris' questions/clarification request from above to the FHIR gForge Issue Tracker [here](http://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=6354&start=0).

**Comment by larrybabb** [comment]
Just heard Nicole Washington (co-chair of the GA4GH G2P) advocate on behalf of the provenance model specified by the W3C in particular the HCLS community profile [here](http://www.w3.org/2001/sw/hcls/notes/hcls-dataset/#s6_4).  The G2P group seems pretty excited and engaged at moving this specification forward and using it to implement their provenance needs.
