### ISSUE TITLE
Gene:officialSymbol

### ISSUE THREAD

**Issue by cbizon** [tnavatar/clingen-data-model#11]
Can we change the name officialSymbol in Gene to just symbol?  What makes it "Official?"

**Comment by srynobio** [comment]
If I had to guess I would say "Official" come from the idea of HGNC Approved Symbol. Given that, we could mimic HGNC and use that term.

Also we could use symbol and note a preferred term to be from HGNC.

http://www.genenames.org/help/symbol-report

**Comment by cbizon** [comment]
I think I would just like to change it to "symbol".

**Comment by tnavatar** [comment]
I would be OK with Chris’ suggestion.
