### ISSUE TITLE
ReferenceSequence.identifier inconsistency

### ISSUE THREAD

**Issue by ronakypatel** [tnavatar/clingen-data-model#115]
The identifier for reference sequence is of dimension 1 here.

http://datamodel.clinicalgenome.org/allele/resource/reference_sequence/

while it is unbounded here

http://datamodel.clinicalgenome.org/main/resources/clingen-xsd/referencesequence.xsd

Chris pointed out in the mail that it should be list.

I think there are pros and cons of both way, e.g. the same transcript can have LRG and NCBI and can be part of same reference sequence. Problem with this approach is there needs to be additional efforts of merging right reference sequences.

**Comment by srynobio** [comment]
I think the cardinality of ReferenceSequence.identifier is just a typo and should be 0..\* then you could add both NCBI and LRG.

**Comment by larrybabb** [comment]
I am not sure I agree.  If the NCBI and LRG reference sequences are
guaranteed to be the same exact reference sequence, then possibly.  Does LRG
and NCBI publish/release/store these sequences separately.  They may be the
same, but if they are in any way different or capable of being different
then they would get different ReferenceSequence Resource records.  If not,
then you can certainly use the versioned identifiers as equivalences as
Shawn suggests below.

From:  Shawn Rynearson notifications@github.com
Reply-To:  tnavatar/clingen-data-model
<reply+000ea21b94ab20274bb7f013b2958e812b2da66dca64269192cf00000001118ec0a09
2a169ce05298179@reply.github.com>
Date:  Tuesday, June 9, 2015 10:56 AM
To:  tnavatar/clingen-data-model clingen-data-model@noreply.github.com
Subject:  Re: [clingen-data-model] ReferenceSequence.identifier
inconsistency (#115)

I think the cardinality of ReferenceSequence.identifier is just a typo and
should be 0..\* then you could add both NCBI and LRG.


Reply to this email directly or view it on GitHub
<https://github.com/tnavatar/clingen-data-model/issues/115#issuecomment-1103
92465> .
