### ISSUE TITLE
SimpleAlleleReglationshipType 'sequentially_related_to question

### ISSUE THREAD

**Issue by larrybabb** [tnavatar/clingen-data-model#116]
I'm not sure if we support this relationship type in the current version of the model.  Please provide an example of its use to clarify.

**Comment by srynobio** [comment]
I added it last as a way to show a relationship between to simple alleles of the same type e.g. two simpleAlleles that denote the same change type, but are two separate recorded changes.

```
                            CanonicalAllele
                                   |
                                   |
 NM_004006.1.g.241T>C  -------  sequentially_related_to ------- NM_004006.2.g.241T>C
 SimpleAllele 1                                                 SimpleAllele 2
```

This is a useful relationship to capture but it is inferable.

**Comment by larrybabb** [comment]
I want to understand this more.  Can you provide an example?  And, can we
add some more documentation and possible sample scenarios to the
documentation so it is clear how and when this value would be used in
practice?

If these are two canonically equivalent simple alleles, then they should be
aggregated by having a common relationship to the same canonical allele.  If
this is the case, then we do not need to wire together the simple alleles
individually.  If it is different then we should clarify how this would be
different then canonically equivalent alleles.  Also, verify that if this
relationship is conveyed in the underlying conceptual model as well.
Currently, the only simple allele relationship in the conceptual model is
between transcript and amino acid alleles.  There is nothing that represents
a relationship between two nucleotide simple alleles as of yet.

From:  Shawn Rynearson notifications@github.com
Reply-To:  clingen-data-model/clingen-data-model
<reply+000ea21b9565c1619e5cc1ee87d0072f462c6a9c864c92d492cf00000001118f28079
2a169ce052ab0e5@reply.github.com>
Date:  Tuesday, June 9, 2015 6:17 PM
To:  clingen-data-model/clingen-data-model
clingen-data-model@noreply.github.com
Cc:  Lawrence Babb larry.babb@gmail.com
Subject:  Re: [clingen-data-model] SimpleAlleleReglationshipType
'sequentially_related_to question (#116)

I added it last as a way to show a relationship between to simple alleles of
the same type e.g. two simpleAlleles that denote the same change type, but
are two separate recorded changes.

CanonicalAllele


Reply to this email directly or view it on GitHub
<https://github.com/clingen-data-model/clingen-data-model/issues/116#issueco
mment-110521032> .
