### ISSUE TITLE
CanonicalAlleleType value list

### ISSUE THREAD

**Issue by larrybabb** [tnavatar/clingen-data-model#117]
The canonical allele type should only have two values in the list "nucleotide" and "amino-acid".  The current list contains the values that would be a permutation of all of the canonical allele complexity and actual canonical allele types.

Further, the xxx-combined value does not work because a CanonicalAllele could never be both a nucleotide and amino acid, based on the model we have designed.

**Comment by larrybabb** [comment]
updated CanonicalAlleleType value list to portray the proper two values (copied from the current SimpleAlleleType value list doc).

**Comment by srynobio** [comment]
I agree about the xxx-combined, for version one, but I think we need to think move it to Milestone 0.2 because we will need to include the type of `complex-nucleotide` and `complex-amino-acid`.

**Comment by larrybabb** [comment]
In order to signify whether a canonical allele is complex or simple, we have
a separate "complexity" attribute.  The canonical allele type is dedicated
to signifying whether or not the canonical allele is amino acid or
nucleotide.  These are two different cross cutting aspects of the canonical
allele class hierarchy.  Let's talk more to get to a common understanding.

From:  Shawn Rynearson notifications@github.com
Reply-To:  clingen-data-model/clingen-data-model
<reply+000ea21b5fb1793c82967933149b05f277eb0887fa16bebb92cf00000001118f2cd69
2a169ce052adfb0@reply.github.com>
Date:  Tuesday, June 9, 2015 6:38 PM
To:  clingen-data-model/clingen-data-model
clingen-data-model@noreply.github.com
Cc:  Lawrence Babb larry.babb@gmail.com
Subject:  Re: [clingen-data-model] CanonicalAlleleType value list (#117)

Reopened #117 
https://github.com/clingen-data-model/clingen-data-model/issues/117 .


Reply to this email directly or view it on GitHub
<https://github.com/clingen-data-model/clingen-data-model/issues/117#event-3
26841815> .

**Comment by srynobio** [comment]
I've got it: http://datamodel.clinicalgenome.org/allele/implementation/value_set_list/canonical_allele_complexity.html
