### ISSUE TITLE
Create additional provenance examples

### ISSUE THREAD

**Issue by bpow** [tnavatar/clingen-data-model#126]
Chris started on some provenance examples, and recommended the following for an initial set:
1. A curator gets a piece of information from a paper (paper_curation.provn)
2. A curator runs a piece of software using some inputs, and enters the results (external_software.provn)
3. A curator pulls a piece of information from an online database search (external_database.provn)
4. A script pulls a piece of information from another database
5. A script performs a calculation based on known information and puts the result into the database​
6. A curator performs a literature search, creating PMID references in the database.

1 through 3 are done, but more are needed...

**Comment by srynobio** [comment]
I'm also currently finishing the Background process archetype.
