### ISSUE TITLE
Generate figures from provenance examples

### ISSUE THREAD

**Issue by bpow** [tnavatar/clingen-data-model#127]
I am working on this, and have been using [pegjs](http://pegjs.org) to parse the prov-n notation to produce input for graphviz. More to follow in terms of integration into the website.

**Comment by srynobio** [comment]
Do we plan on creating prov-o as well?  It may make graph generation easy as well.

**Comment by tnavatar** [comment]
I think prov-n can be transformed to prov-o pretty easily, and that prov-n is a little easier for humans to read and write, so it makes sense for us to start there.

**Comment by bpow** [comment]
Resulting images may look something like this:

![assertion](https://cloud.githubusercontent.com/assets/377006/8286393/2ee34a18-18d7-11e5-9bc2-04c92a021122.png)

**Comment by tnavatar** [comment]
Neat, that’s a lot cleaner than I was expecting. What are you using to generate those?

**Comment by srynobio** [comment]
That's great @bpow

**Comment by bpow** [comment]
I've tried a couple of different approaches. [ProvToolbox](http://lucmoreau.github.io/ProvToolbox/) gets pretty close with its provconvert utility, but the way that it draws the "note" boxes leads to some messiness in the diagrams (it's a relatively easy fix in code, just a switch in the order of two arguments, see my [pull request](https://github.com/lucmoreau/ProvToolbox/pull/119)).

Before I figured out that was what was happening in the provtoolbox diagrams, I went about writing a [parser for provn](https://raw.githubusercontent.com/bpow/pegjs-bonsai/master/examples/provn.pegjs) using [pegjs](http://pegjs.org), which I could then use to generate a similar .dot file to what provtoolbox produced, for input into graphviz. This second approach currently still relies on graphviz (as does provtoolbox), but theoreticaly could be done in client-side javascript using something like viz.js

I'm not sure how much of this to incorporate into the build process, though. I am a bit hesitant to add a large build dependency like provToolbox, so there may be other options to consider.

**Comment by tnavatar** [comment]
I’m pretty OK with adding a large dependency if it saves us work. Also since we’re working in a standard format (PROV-N) not specifically linked to any representation it should be pretty easy to swap it out if we want.

Also I did a quick test, our site works just fine under JRuby (as opposed to the standard C Ruby version). If we’re finding ourselves wanting to incorporate Java libraries in the site build it might make sense to switch over.

**Comment by tnavatar** [comment]
I’d come across https://provenance.ecs.soton.ac.uk/store/documents/85513/ in my searching too, which seems to offer some d3.js based alternatives for visualization. Some of them are pretty rubbish, but I like this one: 

https://provenance.ecs.soton.ac.uk/store/documents/85513/vis/sankey
(there is room for improvement, but to me this feels like the cleanest and most expressive provenance visualization I’ve seen so far).

**Comment by srynobio** [comment]
The D3 example is nice, but most of the D3 stuff is.

**Comment by tnavatar** [comment]
Yeah, D3 tends to style well. I think the thing I like about it is that it visualizes as a flow, read from left to right, with the final assertion at the end and all the evidence leading to it on the left. It doesn’t need to be explained to be understood, which will help a lot in pitching the value of this approach to others.

**Comment by bpow** [comment]
So that people can take a look, I pushed some code to generate diagrams. I haven't gone through the process of structuring links to these within middeman, but if you go to any of the following, you can have a look-see:
- [assertion](http://clingen-data-model.github.io/assertion/examples/assertion.html)
- [background_database](http://clingen-data-model.github.io/assertion/examples/background_database.html)
- [external_database](http://clingen-data-model.github.io/assertion/examples/external_database.html)
- [external_program](http://clingen-data-model.github.io/assertion/examples/external_program.html)
- [literature_search](http://clingen-data-model.github.io/assertion/examples/literature_search.html)
- [paper_curation](http://clingen-data-model.github.io/assertion/examples/paper_curation.html)
- [program_judication](http://clingen-data-model.github.io/assertion/examples/program_judication.html)
