### ISSUE TITLE
Are optional attributes ok in the conceptual model?

### ISSUE THREAD

**Issue by cbizon** [tnavatar/clingen-data-model#13]
For instance, we have in the TranscriptReferenceSequence an integer attribute called codingRegionOffset.   If the transcript is noncoding, then there is no such thing.

So, do we say that the attribute is optional, or do we provide a value to put in to mean "not used" or do we need different classes with/without the attribute?

It's fine in the resource model, but it's a little trickier if one is imagining a relational model...

**Comment by srynobio** [comment]
My thought would be that we can just model how the message would be sent with the understanding that it's a value which can be empty.  In a relational model as long as a field is not noted as NOT NULL it can be empty.

Also now you're making the argument to put the transcript type back in.
