### ISSUE TITLE
Interesting ClinVar example (IUPAC nucleotide codes)

### ISSUE THREAD

**Issue by larrybabb** [tnavatar/clingen-data-model#132]
Steven Harrison sent me this the other day, seems like something we should discuss and make a decision on what our policy is regarding these IUPAC codes...

--- from SHarrison on 6/23/15
I know you’re always looking for interesting ClinVar examples  - I can across something I haven’t seen in ClinVar before: http://www.ncbi.nlm.nih.gov/clinvar/variation/126056/
The entry is for c.4965C>R (Tyr1655Ter). In case you haven’t come across this before the R nucleotide stands for purine – meaning the nucleotide could be an A or G. So this c.4965C>R entry represents both c.4965C>A and c.4965C>G.

I haven’t seen variants in ClinVar using an allele designation that represents multiple nucleotides before...so something to consider. Although may not be too common.

**Comment by srynobio** [comment]
Could this be handle by assiging SimpleAllele.allele to be one of the following [types](https://en.wikipedia.org/wiki/Nucleotide#Abbreviation_codes_for_degenerate_bases)?

**Comment by larrybabb** [comment]
It's a bit more challenging than that, I think.  

If you query clinvar for the associated protein change [p.Tyr1655Ter](http://www.ncbi.nlm.nih.gov/clinvar/?term=Tyr1655Ter) you will see that there are several separate vairants (or alleles) defined.  While we have modeled the data to separate the amino acid allele from the nucleotide allele.  We do not have a consideration for a nucleotide allele that is really a representation of two (or more) distinct nucleotide alleles.  In other words, it would be impossible to place the c.4965C>R simple allele in a single canonical allele, because it represent two different changes at the same location.

As you can see by the above query ClinVar has to duplicate the variants as well and therefore looses the relationship between what should be considered the same variants.

**Comment by srynobio** [comment]
Okay, I may be a bit thick on this, but I still don't understand the issue here.  If I search the ClinVar XML for Steven first example, this is what I find.

``` xml
    <MeasureSet Type="Variant" ID="37936">
      <Measure Type="single nucleotide variant" ID="46492">
        <Name>
          <ElementValue Type="Preferred">NM_000059.3(BRCA2):c.4965C&gt;G (p.Tyr1655Ter)</ElementValue>
        </Name>
        <AttributeSet>
          <Attribute Type="HGVS, coding, LRG" Change="c.4965C&gt;G">LRG_293t1:c.4965C&gt;G</Attribute>
        </AttributeSet>
        <AttributeSet>
          <Attribute Type="HGVS, coding, RefSeq" Change="c.4965C&gt;G">NM_000059.3:c.4965C&gt;G</Attribute>
        </AttributeSet>
        <AttributeSet>
          <Attribute Type="HGVS, genomic, LRG" Change="g.28841C&gt;G">LRG_293:g.28841C&gt;G</Attribute>
        </AttributeSet>
        <AttributeSet>
          <Attribute Type="HGVS, genomic, RefSeqGene" Change="g.28841C&gt;G">NG_012772.3:g.28841C&gt;G</Attribute>
        </AttributeSet>
        <AttributeSet>
          <Attribute Type="HGVS, genomic, top level" Change="g.32339320C&gt;G" integerValue="38">NC_000013.11:g.32339320C&gt;G</Attribute>
        </AttributeSet>
        <AttributeSet>
          <Attribute Type="HGVS, genomic, top level, previous" Change="g.32913457C&gt;G" integerValue="37">NC_000013.10:g.32913457C&gt;G</Attribute>
        </AttributeSet>
        <AttributeSet>
          <Attribute Type="HGVS, non-coding" Change="n.5193C&gt;G">U43746.1:n.5193C&gt;G</Attribute>
        </AttributeSet>
        <AttributeSet>
          <Attribute Type="HGVS, protein">p.Y1655*</Attribute>
        </AttributeSet>
        <AttributeSet>
          <Attribute Type="HGVS, protein">p.Y1655*:TAC&gt;TAG</Attribute>
        </AttributeSet>
        <AttributeSet>
          <Attribute Type="HGVS, protein" Change="p.Tyr1655Ter">LRG_293p1:p.Tyr1655Ter</Attribute>
        </AttributeSet>
        <AttributeSet>
          <Attribute Type="HGVS, protein, RefSeq" Change="p.Tyr1655Ter">NP_000050.2:p.Tyr1655Ter</Attribute>
        </AttributeSet>
```

And the sequence information is given as well 

``` xml
CytogeneticLocation>13q13.1</CytogeneticLocation>
        <SequenceLocation Assembly="GRCh37" AssemblyAccessionVersion="GCF_000001405.25" AssemblyStatus="previous" Chr="13" Accession="NC_000013.10" start="32913457" stop="32913457" display_start="32913457" display_stop="32913457" variantLength="1" referenceAllele="C" alternateAllele="G"/>
        <SequenceLocation Assembly="GRCh38" AssemblyAccessionVersion="GCF_000001405.26" AssemblyStatus="current" Chr="13" Accession="NC_000013.11" start="32339320" stop="32339320" display_start="32339320" display_stop="32339320" variantLength="1" referenceAllele="C" alternateAllele="G"/>
        <MeasureRelationship Type="variant in gene">
```

So we do know the genomic reference and alt, and ter (termination) is given as the amino acid representations.  If someone gave us an message with this _NM_000059.3(BRCA2):c.4965C>R (p.Tyr1655Ter)_ then we should be able to discover from the reference sequence if the sequence is UA or UG, and the wobble position would be R.

When I reviewed your link it says to me three are SimpleAlleles of the same variant (two fully annotated), and one is a protein-only view of the same.

**Comment by larrybabb** [comment]
Not sure what "wobble" position means?  Please explain.

> If someone gave us an message with this NM_000059.3(BRCA2):c.4965C>R (p.Tyr1655Ter) then we should be able to discover from the reference sequence if the sequence is UA or UG, and the wobble position would be R.

I don't think there's any question on how to figure out the reference coordinate information from the c.4965C>R codes.  The question is how you take this singulare representation of a nucleotide and map it to two different changes.  The R means (A or G) at that position, so it is really aggregating two alleles into one represntation (c.4965C>A & c.4965C>G).  It is fine that each of these happens to cause the same amino acid change, or p.Tyr1655Ter, which we have provided for in our model.  But, we have not provided for storing a single representation of 2 nucleotide changes as a single simple allele, becuase they are canonically different alleles at a nucleotide level.

In fact, all the IUPAC codes other than the ones that represent the singular, specific nucleotides A, C, T/U, G are aggregations of multiple codes. Not to even mention that they are ambiguous in that they do not claim to be one or the other specifically, simply that the symbol represents that it may be any of the specified nucleotides or none, depending on the specific symbol.

These ambiguous codes do not fit our precise definitions of an allele.  However, I am not clear as to how we should attempt to handle them, if at all.

**Comment by srynobio** [comment]
[wobble](https://genomevolution.org/wiki/index.php/Codon_wobble_positions)

I think I understand you're point now, which boils down to: we don't definitely know what R is (A/G). 

I think this is why I offered the list, because instead of _storing a single representation of 2 nucleotide change_ we could store R.
