### ISSUE TITLE
'alias:' in page metadata is being used in ways not intended by middleman-alias

### ISSUE THREAD

**Issue by bpow** [tnavatar/clingen-data-model#136]
The middleman-alias plugin generates short html files to redirect to the appropriate page when there is an 'alias:' line in the page metadata. Somehow, there has been a convention within the project to use this for term synonyms instead. For instance, the `source/allele/resource/simple_allele/index.md` file contains the line:

```
alias: simple allele, allele, variant, sequence variant, snv, amino acid variant, dna change, aa change
```

so middleman creates a file called `simple allele, allele, variant, sequence variant, snv, amino acid variant, dna change, aa change` that redirects to `allele/resource/simple_allele`. This is probably not what we mean to do.

We _could_ use a similar data field (`related_terms`?) and use that to keep track of what we are currently keeping track of. Is there a reason to do so?

It looks like @larrybabb  and @tnavatar have added lines like this to documents in the past, so perhaps either of you have an opinion?

**Comment by tnavatar** [comment]
Good catch.

middleman-alias is used for internal redirects. It’s not absolutely necessary to keep this plugin, but I think it would be useful to do so.

I’m with Bradford in creating a similar data field (related_terms would be fine), that serves the same purpose.

**Comment by larrybabb** [comment]
+1
