### ISSUE TITLE
Rename "SimpleAllele" to something that does not include "Simple"

### ISSUE THREAD

**Issue by ppawliczek** [tnavatar/clingen-data-model#141]
I am looking at the diagram http://datamodel.clinicalgenome.org/images/AlleleConceptual.svg and have some doubts. On the right there is SimpleAllele class which is generalization of the classes SimpleNucleotideAllele and SimpleAminoAcidAllele. On the left there are ComplexCanonicalAllele and SimpleCanonicalAllele. So the word "Simple" is used in two different meaning:
- Simple allele - definition of allele in the context of one of the reference - means non-Canonical 
- Simple allele - means non-Complex 

Do I understand it right?

**Comment by larrybabb** [comment]
You are correct.  This is actually a problem which Donna Maglott of NCBI's clinvar team mentioned to us during a previous call.  I believe we should be only using it in the second context you mention above.  We need to rename our "SimpleAllele" term.  

I will put this on our list of things to address.  

For the time being you will need to try to keep these two semantic meanings straight.  Please let me know if you have a recommendation for an alternative term to replace "SimpleAllele".

I am going to edit this issue to reflect the action that we need to address.

**Comment by ppawliczek** [comment]
non-Complex allele = basic allele ? single allele ?
non-Canonical allele = observed allele ?

I think that now it is better to replace the "non-Complex" meaning that "non-Canonical" meaning.

**Comment by srynobio** [comment]
Why don't we just drop the "simple" part.

Allele
NucleotideAllele <- GenomicAllele
TranscriptAllele
AminoAcidAllele

CanonicalAllele <- NucleotideCanonicalAllele

However I think it would be useful and non-confusing to keep the term "Complex".

**Comment by srynobio** [comment]
Changed to AlleleInstance.
