### ISSUE TITLE
primary-transcript-region-type

### ISSUE THREAD

**Issue by ronakypatel** [tnavatar/clingen-data-model#142]
Not sure but is there term that can be used from primary-transcript-region-type value set for indels affecting upstream and downstream regions in addition to coding sequence?

NM_001126115.1:c.-3_13del16
http://www.ncbi.nlm.nih.gov/clinvar/variation/187254/

**Comment by srynobio** [comment]
You would only annotate the region where the change occurred, no where else on the transcript.  A rough guess based on the ClinVar Variation Viewer looks like the change happens in a CDS, but you would need a couple of things to annotate the transcript type correctly:
- A list of all the transcripts in question (or all known).
- A [GFF3](http://www.sequenceontology.org/gff3.shtml) file of genomic features.

Also keep in mind that for the first pass of transforming all the ClinVar data into the model, if ClinVar does not have an annotation for transcript-type you don't (initially) need to worry, it can be compulatally added later.  This is the benefit of having the type in the model.

**Comment by cbizon** [comment]
The problem is that in this case, the deletion spans the start of the transcript.  One could also imagine a frameshift(or non-frameshift) that spans an intron/exon boundary.   I'm starting to wonder if we might have to change the cardinality of primary-transcript-region-type...

**Comment by cbizon** [comment]
Update the text about this
