### ISSUE TITLE
Example names are invalid URIs

### ISSUE THREAD

**Issue by tnavatar** [tnavatar/clingen-data-model#144]
The following aren't valid URIs.

build/main/resources/example-json/CA408-HAP-NM_001171174.1-CX3CR1-c.[841G>A;935C>T].json
build/main/resources/example-json/CA409-HAP-NP_001164645.1-CX3CR1-p.[Val294Ile;Thr280Met].json

Can you rename them to something that is? Then I can rebuild and repost the site.

**Comment by larrybabb** [comment]
I dropped the HGVS haplotype nomenclature from the file name which removed the brackets and semi-colons.  I think that should clear the way.

**Comment by tnavatar** [comment]
Cool, thanks Larry. I rebuilt and published the site with your most recent changes.
