### ISSUE TITLE
sort names in documentation

### ISSUE THREAD

**Issue by cbizon** [tnavatar/clingen-data-model#15]
The list of entities on the left side of the documentation is long enough that some kind of grouping or sorting would help.  An alphabetical sorting would at least make it easy to find things.

**Comment by srynobio** [comment]
I agree this would be much clearer and neater.

**Comment by tnavatar** [comment]
I can add an explicit alphabetical sort, but I think it _is_ already being sorted alphabetically. They're categorized between the resource and the conceptual model, and the styling could use some improvement there. If there's another layer of organization that would make sense, let me know and we can figure it out, perhaps ordering subclasses by their dependencies.

**Comment by cbizon** [comment]
Huh, they are sorted on the io page, but they are not when I view them in middleman.   Any ideas why that would be?

**Comment by tnavatar** [comment]
You’re using Ubuntu, right? I’m guessing that OS X is presenting the list of files in alphabetical order, while Ubuntu isn’t. If this is the issue we should probably use an explicit sort.

**Comment by tnavatar** [comment]
I added an explicit sort to the navbar. Maybe try again?

**Comment by cbizon** [comment]
Looks good.  I also like the changes to the tables.

**Comment by tnavatar** [comment]
Cool. There are a few other styles for tables that you can play with (http://getbootstrap.com/css/#tables). I had to add an explicit class="table"  before each table, then switch to a markdown processor that would support this. It's a little wordier, but not awful I hope.
