### ISSUE TITLE
AlleleInstance.RefCoord.Position jsonld schema update needed.

### ISSUE THREAD

**Issue by larrybabb** [tnavatar/clingen-data-model#151]
Can a jsonld expert please update the jsonld schema file for AlleleInstance so that it reflects the structural changes resulting from issue #143

**Comment by srynobio** [comment]
@larrybabb I can help with this update.  Could you give me a heads-up on the location of the files.

**Comment by larrybabb** [comment]
2 files - very similar though.

[example-jsonld/AlleleInstance.jsonld](../tree/master/source/main/resources/example-jsonld/AlleleInstance.jsonld)
[example-jsonld-nofhir/AlleleInstance.jsonld](../tree/master/source/main/resources/example-jsonld-nofhir/AlleleInstance.jsonld)
