### ISSUE TITLE
Terms for Penetrance

### ISSUE THREAD

**Issue by cbizon** [tnavatar/clingen-data-model#159]
We need penetrance data for assertions.  Penetrance can be defined numerically, but more often is given some qualitative levels.   In UNC's parsing of ACMG guidelines, these terms were picked out:

1) Complete
2) Incomplete
3) Reduced

Questions: 
1) What is the difference between Incomplete and Reduced?
2) Is there an external controlled vocab we can use?
3) Do we want the ability for quantitative values?

**Comment by bpow** [comment]
Oops, the "Incomplete"/"Reduced" ambiguity is something I had meant to discuss with Tasha. I'm really not sure how far we can go with this from a quantitative standpoint-- penetrance is so infrequently reported and subject to numerous potential unmeasured factors even when attempts are made to measure it. I would lean towards just having "complete" and "incomplete", where if it is the latter then an analyst or machine learning algorithm would be tipped off that at least some individuals with the genotype may not have the associated phenotype.

I am not aware of an SO term that we could use here. HPO has HP:0003829 for incomplete penetrance and a child term HP:0003831 for age-dependent penetrance (which we could also consider including), but interestingly has no term for complete penetrance.

Any thoughts from @srynobio from the terminology standpoint?

**Comment by cbizon** [comment]
Yeah, the quantitative would be a reach, but it is out there of course for important genes (BRCAs...).  I guess part of the question is whether the particular values would be something that one would want to say were used in the evaluation of a rule.

"Age dependent" seems important, especially for cancers?   But it also seems like age is tied up in many estimates of penetrance in a way that isn't always explicit.  e.g. What does it mean that something like Huntington's  or Usher syndrome is completely penetrant?

If we don't go quantitative, is complete/incomplete (and age dependent?)  good enough.  The controlled vocabulary known as Wikipedia has 4 categories:

Complete Penetrance
High Penetrance
Incomplete/Reduced Penetrance
Low Penetrance

but there is no numerical idea of what these actually mean.

**Comment by cbizon** [comment]
What does the Gene Curation WG think?
