### ISSUE TITLE
Implementing Updated Models

### ISSUE THREAD

**Issue by ronakypatel** [tnavatar/clingen-data-model#162]
I have started process of implementing new models for registry. In that regards, There is inconsistency in documentation. At some places it is allele Instance (http://datamodel.clinicalgenome.org/development/allele/implementation/examples/) and others it is contextual allele (http://datamodel.clinicalgenome.org/development/allele/resource/contextual_allele/). I really am not sure what we moved to? 

Value set list of primaryTranscriptRegionType shows interior_intron as acceptable code (http://datamodel.clinicalgenome.org/development/allele/implementation/value_set_list/primary_transcript_region_type.html), while the example uses intron which is nowhere in the value set list (http://datamodel.clinicalgenome.org/development/allele/implementation/examples/AI301.html)

**Comment by cbizon** [comment]
Thanks for pointing these out.   We have moved to ContextualAllele, so I will update the places that say Allele Instance (darn, I thought I already had them all!)

Shawn, can you deal with the value sets?

**Comment by srynobio** [comment]
The Value Set has been updated.

**Comment by ronakypatel** [comment]
The value set list is still different:

http://datamodel.clinicalgenome.org/development/allele/implementation/value_set_list/primary_transcript_region_type.html

http://datamodel.clinicalgenome.org/development/allele/implementation/examples/AI301.html

May be needs recompilation? Or the example uses wrong primaryTranscriptRegionType.

**Comment by ronakypatel** [comment]
Similarly here

http://datamodel.clinicalgenome.org/development/allele/implementation/examples/AI310.html

Exon is not there in the primary transcript region type.

**Comment by srynobio** [comment]
Okay @ronakypatel I've updated the exon examples, the intron examples were updated but the site needs a rebuild.  If you find any more please let me know.
