### ISSUE TITLE
Broken links in resource model pages

### ISSUE THREAD

**Issue by bpow** [tnavatar/clingen-data-model#165]
For instance, on http://datamodel.clinicalgenome.org/development/allele/resource/

The link to CanonicalAllele points to http://datamodel.clinicalgenome.org/allele/resource/canonical_allele/ (which gives a 404)

This is missing the "development" part of the path, it should point to http://datamodel.clinicalgenome.org/development/allele/resource/canonical_allele/

@tnavatar I think this has to do with the setup for building/publishing multiple versions of the documentation.

**Comment by bpow** [comment]
For some reason, altough `link_to` is being used in `allele/resource/index.md.erb`, and `link_to` is being set to use relative links (in `config.rb`), an absolute, rather than relative link is being used, and this breaks when using the 'development' or '0.1' prefix.

@tnavatar : any thoughts? It looks like you may have had to work around `link_to` issues before.

**Comment by bpow** [comment]
Assigning to @tnavatar, but let me know if you want me to look into this further.

**Comment by bpow** [comment]
You might be able to try adding
`set :http_prefix, ENV['MIDDLEMAN_PREFIX'] if ENV['MIDDLEMAN_PREFIX']` in the `:build` section of `config.rb`, then in the build script call `MIDDLEMAN_PREFIX=$version bundle exec middleman build`.

I'm not sure how that will interact with they way you had to handle relative links before this, though.

**Comment by bpow** [comment]
@tnavatar : we talked about adding an issue for this during the call today, but I see that I already had ;)

**Comment by bpow** [comment]
This looks to be fixed.

**Comment by bpow** [comment]
Apparently, this is actually not fixed, and we noticed again on the call today. Re-opening.

**Comment by bpow** [comment]
My best guess (after trying some fiddling) is that middleman's creation of relative links is not able to handle links to or filenames with '>' in them (that get url-escaped for publishing). Does this seem right to you, @tnavatar ?

If this is the case, can we just go ahead and rename those files to not have the full hgvs expression? Thoughts from @larrybabb or @cbizon ?

**Comment by tnavatar** [comment]
It’s possible, I haven’t encountered that case yet myself. > isn’t an acceptable character in RFC1738, so we should rename these files.

**Comment by larrybabb** [comment]
Sure, lets replace the > with an underscore (like c.500G_A).  It isn't critical, just nice for the user to see a filename that communicates the variant that is contained within it. It does not need to be precise HGVS.

@tnavatar Feel free to change or let me know if you'd like me to.

**Comment by bpow** [comment]
I think I fixed this with ee1e894 by escaping the > with %3E in the uri references. (which is also what later versions of middleman would do)
