### ISSUE TITLE
Clarifications on the Coordinate Numbering page

### ISSUE THREAD

**Issue by rrfreimuth** [tnavatar/clingen-data-model#166]
I re-read the page on coordinate numbering (http://datamodel.clinicalgenome.org/0.1/allele/discussion/coordinate_numbering.html) (love it, BTW) and I have a few suggestions.

In the Intronic Coordinates section, the first figure uses the Interval Method (as described in the previous section).  It might help readers to explicitly state this.

In the same figure, the "Intronic Left" and "Intronic Right" designations are relative to the transcript orientation, but this may differ from the genomic/chromosomal orientation if the gene is on the reverse strand.  We may want to state this, even though it may be obvious, as it would be very easy for someone to forget which end is which in those cases and then the numbering would be wrong.

In the same figure, we may want to change the intron sequence to "gtacag" so it follows the cannonical pattern of "gt...ag".  The current example could be confusing for readers that are paying attention to the exon/intron boundaries.

In the second figure in the Intronic section, it might help readers to understand the difference between the coordinate columns if additional labels were included in their headers.  In particular, "start" and "end" are exon-based (interval method) and the "offsetStart" and "offsetEnd" columns refer to the intronic coordinates.

The "Intronic Right" and "Intronic Left" examples clearly map to the previous table, but the "Intronic Long" label does not.  A different label for that example might avoid confusion for anyone looking for that term in the previous table.  In addition, in that example there is no orientation (offsetDirection) provided.  It should be "+", unless that cell was blank for a reason I did not appreciate.

Finally, if the intronic sequence is changed in the previous figure, the sequences in the "ref" column might need to be updated.

Thanks!!

**Comment by larrybabb** [comment]
@cbizon is the author of this doc, so I will defer to him for final decisions.  I did some of the figure work so I can help out with the changes if any are decided.

They all seem like good suggestions to me, but again @cbizon will need to sign off on these.

Thanks for reviewing this so thoroughly.  It will be a document that surfaces over and over I think as other groups get into the weeds on these things, so it is important to have it right.
