### ISSUE TITLE
Genomic Reference Sequences

### ISSUE THREAD

**Issue by rrfreimuth** [tnavatar/clingen-data-model#167]
GenomicRefSeq (abstract class) is the parent of both ChromRefSeq (e.g., 1-22, X, Y, mito) and GenRefSeq (e.g., RefSeqGene, LRG).

How would one represent a NC_ or NT_ sequence?

**Comment by larrybabb** [comment]
NC_ = ChromRefSeq I believe.  I’m not sure about NT_.

**Comment by rrfreimuth** [comment]
ChromRefSeq is at the level of an entire chromosome, whereas GeneRefSeq represents only the seq associated with the boundaries of a given gene.  I think we need a way to represent something in between - a chunk of a chromosome that may contain one or more genes (or fragments thereof).

Per discussion during DMWG call on 3/9/16:  General agreement.  Will leave this issue open and will address when we go back to clean up the model.
