### ISSUE TITLE
Markdown: Links in the description are not being rendered correctly.

### ISSUE THREAD

**Issue by cbizon** [tnavatar/clingen-data-model#17]
eg in Genomic Reference Sequence:
## the markdown looks like:

title: GenomicReferenceSequence
description: A [ReferenceSequence](reference_sequence.html) describing full or partial chromosomal DNA.

---

If you look in the html, the description still has the []() stuff and not a hyperlink.

But if I take that []() phrase out of the header, it works fine.

**Comment by cbizon** [comment]
Hah, note that I didn't escape my comment properly, so it's a little hard to understand....

**Comment by tnavatar** [comment]
I get what you mean with this. I think the 'fix' for now is to use straight HTML links. Looking back at the issues for Middleman, it seems like the folks who wrote it made a decision not to run any preprocessor over the front matter in pages, so we can't use Markdown (or anything else) there.
