### ISSUE TITLE
ProposeInterpretation

### ISSUE THREAD

**Issue by cbizon** [tnavatar/clingen-data-model#173]
ProposeInterpretation:

1) I'm not sure why Condition is here?

2) But maybe the workspace should be?  So the interpretation is then understood to be the combination of the outcomes, but within the context of all the other evidence available?

3) One thing I heard Heidi talk about at the Variant Curation call was that ACMG also allows the interpreter to explicitly move an outcome up or down in importance.  So if something is moderate, the interpreter may have some reason to upgrade it to strong or downgrade it to whatever is below moderate.  I guess that this would be another activity (RegradeOutcome?)

**Comment by bpow** [comment]
Pretty sure this issue is obsolete... I don't think we have a `ProposeInterpretation` object anymore.
