### ISSUE TITLE
Ontology for functional data types

### ISSUE THREAD

**Issue by cbizon** [tnavatar/clingen-data-model#179]
In the FunctionalData entity, we have an attribute dataType.  The idea was that would be populated using some ontology or another.  So what is it?

Some possiblities:
EFO ( http://www.ebi.ac.uk/efo/ ) is already used in gene curation.  But I don't see a term, for instance, for something like binding assay.
BAO ( http://bioassayontology.org/ )
OBI (http://obi-ontology.org/page/Main_Page)

There are some examples of what we need in the PS3 examples.

**Comment by srynobio** [comment]
Depending on what level of functionality you want to add [SO](http://www.sequenceontology.org/browser/current_svn/term/SO:0001536) offers some terms as well.
