### ISSUE TITLE
sequence_ontology header

### ISSUE THREAD

**Issue by cbizon** [tnavatar/clingen-data-model#18]
In ReferenceGenome ( and probably others) there is a sequence_ontology tag in the header, but it is not being rendered in the html page.

**Comment by srynobio** [comment]
This is a syntax error.  You can't have a space between the two elements.

**Comment by cbizon** [comment]
I'm confused... Does your comment above relate to this issue, or was it meant for another one?

**Comment by srynobio** [comment]
Sorry, yes it somewhat related.  I saw that in the ReferenceSequence (http://clingen-data-model.github.io/allele/conceptual/reference_sequence.html) page some html was not being rendered correctly, and I linked the two.

**Comment by tnavatar** [comment]
Added the link to the title in ea7e8db.
