### ISSUE TITLE
Review overview text for Allele Registry summary

### ISSUE THREAD

**Issue by sgoehringer** [tnavatar/clingen-data-model#183]
It looks that the img is broken on this page as well as a reference and link to the Cherry lab should be updated.

https://github.com/clingen-data-model/allele/blob/master/source/implementation/applications/index.md

**Comment by nafisakhandaker** [comment]
Image URL is correct. But it is not displaying probably because it is a .png file. If you click on the image it opens it.
Cherry Lab link is pointing to https://cherrylab.stanford.edu/. What should be the new link?

**Comment by sgoehringer** [comment]
Interesting... maybe it was a internet burp yesterday.  It works fine today.  Thanks for looking into it!
