### ISSUE TITLE
broken links!

### ISSUE THREAD

**Issue by bpow** [tnavatar/clingen-data-model#187]
Many broken links:

| link | referenced in |
| ---- | ------ | 
| primary-transcript-region-type.html | implementation/value_set_list/ancillary_transcript_region_type.html |
| primary-amino-acid-change-type.html | implementation/value_set_list/ancillary_amino_acid_change_type.html |
| reference_sequence/index.html | conceptual/contextual_allele/index.html |
| ../../discussion/coordinate_numbering.html | conceptual/contextual_allele/reference_coordinate.html |
| genomic_reference_sequence.html | conceptual/contextual_allele/transcript_reference_coordinate.html |
| genomic_reference_sequence.html | conceptual/contextual_allele/transcript_reference_coordinate.html |
| genomic_reference_sequence.html | conceptual/contextual_allele/transcript_reference_coordinate.html |
| canonical_allele.html | conceptual/contextual_allele/reference_coordinate.html |
| ../reference_coordinate.html | conceptual/contextual_allele/position.html |
| external_position | conceptual/contextual_allele/position.html |
| ../../discussion/coordinate_numbering.html | conceptual/contextual_allele/position.html |
| ../reference_coordinate.html | conceptual/contextual_allele/internal_position.html |
| ../reference_coordinate.html | conceptual/contextual_allele/external_position.html |
| ../reference_sequence.html | conceptual/contextual_allele/internal_position.html |
| ../reference_sequence.html | conceptual/contextual_allele/external_position.html |
| simple_canonical_allele.html | conceptual/contextual_allele/genomic_contextual_allele.html |
| genomic_reference_sequence.html | conceptual/contextual_allele/external_position.html |
| nucleotide_contextual_allele.html | conceptual/canonical_allele/simple_nucleotide_canonical_allele.html |
| simple_amino_acid_allele.html | conceptual/canonical_allele/simple_amino_acid_canonical_allele.html |
| genomic_allele_reference_coordinate.html | conceptual/reference_sequence/genomic_reference_sequence.html |
| reference_sequence.html | conceptual/reference_sequence/genomic_reference_sequence.html |

# Update:
These have now been fixed:

| link | referenced in |
| ---- | ------ | 
| contextual_allele.html | conceptual/contextual_allele/amino_acid_contextual_allele.html |
| contextual_allele.html | conceptual/contextual_allele/transcript_contextual_allele.html |
| contextual_allele.html | conceptual/contextual_allele/genomic_contextual_allele.html |
| contextual_allele.html | conceptual/contextual_allele/nucleotide_contextual_allele.html |
| contextual_allele.html | conceptual/contextual_allele/nucleotide_reference_coordinate.html |
| contextual_allele.html | conceptual/contextual_allele/genomic_reference_coordinate.html |
| contextual_allele.html | conceptual/contextual_allele/amino_acid_reference_coordinate.html |
| contextual_allele.html | conceptual/contextual_allele/transcript_reference_coordinate.html |
| contextual_allele.html | conceptual/contextual_allele/reference_coordinate.html |

**Comment by bpow** [comment]
@larrybabb , @cbizon , @nafisakhandaker : thoughts on how we should address these? Some are just instances were a file is being referenced instead of the directory (or appropriate index.html: like the ones referring to contextual_allele.html). Others are just missing, and may need to be made from info in the schema/model.

**Comment by larrybabb** [comment]
Can I take ownership of this between now and Jan 3rd?  If so, I do have an idea on how to deal with this in a more sane manner.  I do think we may still want to move things around and I'd prefer not to have this continue to happen.

@bpow please approve or deny my request. I don't want to spend time on this if you will be doing the same.

**Comment by sgoehringer** [comment]
@larrybabb I have a few ideas as well based on .htaccess and rewrite rules but I’m not certain it will work in the Github site account. 

Let me know if my 2 cents would be helpful. 

Scott

**Comment by larrybabb** [comment]
I was thinking of doing something like this (super high level)

Put all the Entity pages in a single directory where there is one named (.md) file for each entity.  This structure would not necessarily reflect the menu outline we use to navigate on the right-hand side.

Organize our menus on the right-hand side (however we want) - but as is for now.  Use "redirects" in proxy pages (which can be .md or .html) to point to the real page.

This way a single entity can be found by navigating down one of several paths in our outline.

I've found that our outline struggles when it tries to demonstrate a "kind of hierarchy" and a "kind of grouping" approach.  What is "Core",  Do we really want to show "DomainEntity" (it isn't in our schema or model - really).  

Anyway, I think this approach will eliminate or reduce the issues surrounding broken links going forward and decouple our model from our website layout.

Feel free to bash this idea.  @sgoehringer I'm all ears on your rewrite rules.  Don't know about .htaccess though.  Please email me with details or let me know if we need to chat directly.

**Comment by sgoehringer** [comment]
I quickly looked and Github doesn’t look to support rewrite rules, at least in a traditional way... I can snoop around a little more but I think your plan is where to start. 

Scott

**Comment by bpow** [comment]
@larrybabb : I think you may be conflating these broken links with the ones in the interpretation model repo. I fixed the ones in interpretation, and they should be more robust to moving directories around (used erb around the md to allow for the middleman link_to helper..., since it's a static site and rewrite rules don't work).

This issue has to do with the allele model-- I think some were just people being sloppy making the links, and others are pointing to files that don't appear to exist.

**Comment by bpow** [comment]
Updated original issue to reflect some fixes

**Comment by larrybabb** [comment]
Got it. Thanks for clarifying. I’ll still clean it up over the holiday.

**Comment by larrybabb** [comment]
done.
