### ISSUE TITLE
Complete SimpleAllele

### ISSUE THREAD

**Issue by tnavatar** [tnavatar/clingen-data-model#2]
Comments from Shawn
This is all great and I agree overall with with how it’s worded but I have one thought:
Given that we state _"SimpleAllele must be either a GenomicSimpleAllele, a TranscriptSimpleAllele, or a ProteinSimpleAllele”_, would each sub-class benefit from having a “type(Effect/MC)” and “feature” field.

**Comment by srynobio** [comment]
Closed due to no response.
