### ISSUE TITLE
Provenance on canonical alleles

### ISSUE THREAD

**Issue by cbizon** [tnavatar/clingen-data-model#24]
I think we want to add some information about where canonical alleles come from.   Options

1) Put some info in e.g. a FHIR id.
2) Add W3C prov,
     - make canonicalizer an entity?

**Comment by tnavatar** [comment]
Good point. So in this context dbSNP could be one source, and, say Aleks’ group could be another?

**Comment by cbizon** [comment]
Correct.

**Comment by tnavatar** [comment]
I really like this idea, actually. Allowing ourselves to use multiple sources of canonical alleles (and recording the provenance) frees us from issues related to dbSNP, or any system created internally to ClinGen.

**Comment by cbizon** [comment]
This is in both the conceptual and resource models now.
