### ISSUE TITLE
AminoAcidChangeType

### ISSUE THREAD

**Issue by cbizon** [tnavatar/clingen-data-model#26]
AminoAcidChangeType is listed as a child of gene variant.  That's fine, I guess.  But we need a unique value for each amino acid allele that will include this kind of terms (or synonyms):
nonsense
stop-loss
deletion
frameshifting deletion
insertion
frameshifting insertion

**Comment by srynobio** [comment]
Working on this one.  And I will keep this in mind.

**Comment by cbizon** [comment]
Closing.
