### ISSUE TITLE
simplenucleotideallele.nucleotidechangetype

### ISSUE THREAD

**Issue by cbizon** [tnavatar/clingen-data-model#27]
Is listed in the docs as a child of allele_position

A. Is allele_postition in the SO yet?  Is there a draft SO or something we can point at?
B. If I remember, it's the sequence_alteration terms (+no_alteration).  If that's right, then there are a bunch of terms that are not appropriate: UPD (+children), CNV(+children), inversion, structural alteration.   This is not as simple as allowing a set of values like transcriptrefcoord.regionType; it is that given our model, these would be incorrect values for us.
C. We may also want to make a similar unique/exhaustive list, because of the children of deletion/insertion.
D. Is the difference between substitution and indel simply whether the length of the alt is the same as the length of the ref?

**Comment by srynobio** [comment]
A first version of the list has been committed we can review on call.
