### ISSUE TITLE
Do we want provenance on non-canonical alleles

### ISSUE THREAD

**Issue by cbizon** [tnavatar/clingen-data-model#28]
For instance, to track that we got a particular simple allele from clinvar. or from a paper, or from a clinical lab.

**Comment by tnavatar** [comment]
To me that felt like a feature of whatever system is using the allele model, and not to be included in the allele model itself. Happy to hear arguments to the contrary though.

**Comment by cbizon** [comment]
The main reason that i can think of is if one imagines a broader network of systems beyond just ClinVar/ClinGenDB.    So just as an example, a curation app pulls a variant from clingendb, and wants to know where it came from.   That message about where it came from should be modeled.  Further, if you have a really decentralized system, you might want to pass around that I got this variant from clingen, but it originally came from clinvar...

**Comment by tnavatar** [comment]
I can see that as a useful feature. I do wonder whether that type of provenance is always attached to a SimpleAllele rather than a CanonicalAllele. For instance, I think a reference to an allele from ClinVar would in fact be a reference to a CanonicalAllele.

**Comment by cbizon** [comment]
Yeah, that is probably right.  I wonder if having simple allele provenance would help in sorting out old / conflicting canonical alleles, or if it's just a bunch of pointless complexity.  Probably the latter.

**Comment by srynobio** [comment]
Another level of power adding provenance in the above fashion is it would allow the implementer the power to rank submission quality over time.  This information would also be helpful to send back to the original aggregates i.e. ClinVar, so they could modify review status, etc.

**Comment by cbizon** [comment]
This is in the conceptual and resource models.
