### ISSUE TITLE
RelatedReferenceSequence reference in Gene resource

### ISSUE THREAD

**Issue by tnavatar** [tnavatar/clingen-data-model#29]
I see that there's a multiple reference to the RelatedReferenceSequence in the gene resource. While this is definitely something that can be attached to a gene, is there a particular reason for attaching it to the resource in this case?

**Comment by larrybabb** [comment]
I'm not sure we need it actually.  I suppose it would be useful to return a gene record and have it contain the full list of transcript or gene reference sequences it is related to.  But, I can't say for sure it is necessary.

**Comment by tnavatar** [comment]
My feeling is that if we can search reference sequence by gene, and vice versa, that might address your use case without having to include the relationship in the resource itself. Just wondering if there might be other reasons for it.

On Feb 24, 2015, at 12:46 PM, larrybabb <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm not sure we need it actually. I suppose it would be useful to return a gene record and have it contain the full list of transcript or gene reference sequences it is related to. But, I can't say for sure it is necessary.

—
Reply to this email directly or view it on GitHubhttps://github.com/tnavatar/clingen-data-model/issues/29#issuecomment-75807283.

IMPORTANT WARNING: The information in this message (and the documents attached to it, if any) is confidential and may be legally privileged. It is intended solely for the addressee. Access to this message by anyone else is unauthorized. If you are not the intended recipient, any disclosure, copying, distribution or any action taken, or omitted to be taken, in reliance on it is prohibited and may be unlawful. If you have received this message in error, please delete all electronic copies of this message (and the documents attached to it, if any), destroy any hard copies you may have created and notify me immediately by replying to this email. Thank you.

Geisinger Health System utilizes an encryption process to safeguard Protected Health Information and other confidential data contained in external e-mail messages. If email is encrypted, the recipient will receive an e-mail instructing them to sign on to the Geisinger Health System Secure E-mail Message Center to retrieve the encrypted e-mail.
