### ISSUE TITLE
Complete CanonicalAllele

### ISSUE THREAD

**Issue by tnavatar** [tnavatar/clingen-data-model#3]
Comment from Shawn:

Just for my clarification when we state this: _"Furthermore, if a genomic variant occurs in a transcript, the allele may be defined with respect to either the genomic sequence, or the transcript sequence.”_ we are assuming annotations at two separate sub-classes, TranscriptSimpleAllele and GenomicSimpleAllele, correct.

**Comment by srynobio** [comment]
Closed due to no response.
