### ISSUE TITLE
Model Change: classification pattern

### ISSUE THREAD

**Issue by larrybabb** [tnavatar/clingen-data-model#32]
I am inserting two new subclasses NucleotideReferenceCoordinate and NucleotideReferenceSequence into the model.  These have no major significance other than providing a consistent pattern for classifying our Resources when rolling these classes up in the Resource model.  Conceptually they exist (IMO). So, now across the conceptual model there will be a "NucleotideX" class level, which I will refer to as the sequenceClass.  sequenceClass will always be either nucleotide or amino acid.  Beneath all of the Nucleotide classes there will always be two subclasses GenomicX and TranscriptX.  I will refer to these as nucleotideSequenceClass and the values will be either genomic or transcript.  

There are two other classification code value sets needed in the resource model.  First, genomicSequenceClass (used only in the ReferenceSequence hierarchy) which will be either chromosome or gene (thus far).  Lastly, the canonicalAllele subclasses related to complexity will be referred to as alleleClass, which will currently be either simple or complex (we may eventually add structural to this).

Let me know your thoughts.  I will check in the changes in Visual Paradigm shortly.

**Comment by cbizon** [comment]
Seems reasonable.

**Comment by tnavatar** [comment]
We've made this change, closing issue.
