### ISSUE TITLE
Bare Simple Allele

### ISSUE THREAD

**Issue by cbizon** [tnavatar/clingen-data-model#34]
This is in the scope and usage for simple allele (resource):

A SimpleAllele does not exist outside the context of a CanonicalAllele; a CanonicalAllele is represented by one or more simple alleles.

Is that true?   How can it be true if simple allele is a resource?  Suppose e.g. a curation app wants to submit a variant to allele registry.  It will send a non-canonicalized simple allele.

**Comment by srynobio** [comment]
_A SimpleAllele does not exist outside the context of a CanonicalAllele; a CanonicalAllele is represented by one or more simple alleles_

Given that you would not have a canonical allele without having 1..\* simple alleles, and that you could have a simple allele which has yet to be Canonicalized.  Would it be better to say:

_A CanonicalAllelle does not exist outside the context of a SimpleAllele; a CanonicalAllele is represented by one or more simple alleles._

**Comment by larrybabb** [comment]
I agree with that.

From:  Shawn Rynearson notifications@github.com
Reply-To:  tnavatar/clingen-data-model
<reply+000ea21b91caae4919985d91f4156a7661c5c8fc5f70917f92cf000000011105e9cb9
2a169ce03839269@reply.github.com>
Date:  Wednesday, February 25, 2015 2:51 PM
To:  tnavatar/clingen-data-model clingen-data-model@noreply.github.com
Subject:  Re: [clingen-data-model] Bare Simple Allele (#34)

A SimpleAllele does not exist outside the context of a CanonicalAllele; a
CanonicalAllele is represented by one or more simple alleles

Given that you would not have a canonical allele without having 1..\* simple
alleles, and that you could have a simple allele which has yet to be
Canonicalized.  Would it be better to say:

A CanonicalAllelle does not exist outside the context of a SimpleAllele; a
CanonicalAllele is represented by one or more simple alleles.

‹
Reply to this email directly or view it on GitHub
<https://github.com/tnavatar/clingen-data-model/issues/34#issuecomment-76041
678> .

**Comment by tnavatar** [comment]
Sounds reasonable to me too. A lot of the wording of the resources was done just to get something up quickly, so I'm glad people are looking at it now. At some point we should discuss the resources in the context of the discussion we had with Aleks' team.
