### ISSUE TITLE
Doc links between conceptual and resource

### ISSUE THREAD

**Issue by cbizon** [tnavatar/clingen-data-model#35]
I think it would be nice to have some hyperlinks between the conceptual and resource models, at least to the root entities.  (Might be nice for any conceptual entity to link to whatever resource it gets rolled up into as well..)

**Comment by larrybabb** [comment]
Tristan - could you take this.  It should be pretty easy.  Not sure if it should be driven by scripting or not.  No worries if you don't, I'll try to get to it when I can if you don't first.  

I started with a link under the Resource and Conceptual diagrams that point back and forth between the main entity pages only.  I suppose we should add links under the Resource diagram to all of the specific conceptual entity pages related to that one Resource.  And find a place on every Concpetual entity page to jump to the encompassing Resource entity page.

**Comment by tnavatar** [comment]
Sure, I’m thinking these links should have a prominent place, so the connections are obvious between the two. I’ll see what I can do.
