### ISSUE TITLE
Should we apply the primary/ancillary pattern to AAChangeType and NucleotideChangeType?

### ISSUE THREAD

**Issue by larrybabb** [tnavatar/clingen-data-model#47]
From: Shawn Rynearson shawn.rynearson@gmail.com
Date: Wednesday, March 11, 2015 10:38 PM

I think it makes sense as we gain the same power, but I'm open to discussion.

--Shawn

On Wed, Mar 11, 2015 at 4:27 PM, Babb, Larry J. lbabb@geneinsight.com wrote:
I think I missed something. Please clarify if I have this correct.

We decided to have a primaryTranscriptRegionType for the transcript reference coordinate entities (required), as well as, an optional ancillaryTranscriptRegionType attribute to allow for zero to many more detailed representations of the primary one.

I assume the above is correct…

However, did we decide to do this for the amino acid change type and nucleotide change type?  I thought the above approach was specifically for region type not the change type fields.

Please clarify.
-- Larry

**Comment by srynobio** [comment]
``` JSON
{
    "_comment": "maybe replace primary with list?",
    "nucleotideChangeType": {
        "coding": [
            {
                "system": "http: //www.sequenceontology.org/",
                "code": "SO: 1000002",
                "display": "substitution",
                "list": "primary",
                "valueSet": {
                    "reference": "/ValueSet/NucleotideChangeType"
                }
            },
            {
                "system": "http: //www.sequenceontology.org/",
                "code": "SO: 0000694",
                "display": "SNP",
                "list": "ancillary",
                "valueSet": {
                    "reference": "/ValueSet/NucleotideChangeType"
                }
            }
        ]
    }
}
```

**Comment by larrybabb** [comment]
Let's go through this together at an upcoming meeting.  Two points to review
beforehand are:

The "Coding" datatype in the FHIR spec does not have a "list" attribute, and
The "valueSet" attribute of the Coding datatype should point to a value set
that has a specific list of values that is constrained for the attribute it
is defined by.  In other words, we will need two separate value sets, one
for the primary attribute and one for the ancillary.  The
primaryXXXChangeType value set will contain a precise controlled list of SO
terms, while the ancillaryXXXChangeType may be defined to be any SO
sub-terms for a given term in the ontology (for example).  If you look
around at the value sets in the FHIR spec you will see some that are
specific fixed lists and others that are linked to coding systems like
SNOMED (and they don't bother listing the codes because they are too
numerous and always growing).

In conjunction with this issue there is the whole discussion about FHIR's
use of value sets, and the RDF/JSON-LD/Ontology question as well.  I believe
one aspect that is conflating this particular issue of primary and ancillary
having a patterned relationship in our model is the fact that we are
defining our resources with a built in constraint on the XXXChangeType and
RegionType attributes.   In truth, from a specification standpoint we should
"probably" just have one attribute (no primary or ancillary qualifier) for
each separate attribute and then define what is called a "Profile" (using
FHIR terms) to constrain the value set that can be used in our particular
allele registry application.  We seem to be in the middle of defining a
Resource that is somewhat reusable and "standard" vs. one that is being
designed specifically for an allele registry application.  This can create
challenges that are not necessarily obvious to everyone working on the model
(IMO). 

Anyway, the good news is that we are continuing to discuss and work through
all of these issues, which is difficult but necessary work, if we want to
help the clinical genetics community move forward.

From:  Shawn Rynearson notifications@github.com
Reply-To:  tnavatar/clingen-data-model
<reply+000ea21bbf40aea6fad9edb46d7d0c16c8c4818caa563e4292cf000000011119b7a19
2a169ce039fe864@reply.github.com>
Date:  Thursday, March 12, 2015 4:22 PM
To:  tnavatar/clingen-data-model clingen-data-model@noreply.github.com
Cc:  Lawrence Babb larry.babb@gmail.com
Subject:  Re: [clingen-data-model] Should we apply the primary/ancillary
pattern to AAChangeType and NucleotideChangeType? (#47)

{
    "_comment": "maybe replace primary with list?",
    "nucleotideChangeType": {
        "coding": [
            {
                "system": "http: //www.sequenceontology.org/",
                "code": "SO: 1000002",
                "display": "substitution",
                "list": "primary",
                "valueSet": {
                    "reference": "/ValueSet/NucleotideChangeType"
                }
            },
            {
                "system": "http: //www.sequenceontology.org/",
                "code": "SO: 0000694",
                "display": "SNP",
                "list": "ancillary",
                "valueSet": {
                    "reference": "/ValueSet/NucleotideChangeType"
                }
            }
        ]
    }
}
‹
Reply to this email directly or view it on GitHub
<https://github.com/tnavatar/clingen-data-model/issues/47#issuecomment-78600
422> .
