### ISSUE TITLE
Complex canonical allele example(s) needed.

### ISSUE THREAD

**Issue by larrybabb** [tnavatar/clingen-data-model#49]
We should generate a practical example of a complex allele and the supporting examples that it would reference.

**Comment by tnavatar** [comment]
I know there aren't many fans of the star allele nomenclature, but they do provide clinically relevant examples of assertions made on complex alleles that could translate into our model. Here's a possible start: 

http://www.cypalleles.ki.se/cyp2c19.htm

**Comment by larrybabb** [comment]
I added the first two complex canonical allele examples in the json examples only.

See the github issue #112 for details.

We probably could use some haplotype examples to support PGx, maybe on gene TPMT since it is related to the work being done in parallel at the IoM.
