### ISSUE TITLE
Questions About Primary Transcript Region Type

### ISSUE THREAD

**Issue by cbizon** [tnavatar/clingen-data-model#50]
1) What the region type for a location in a non-coding transcript?   I would imagine something like "UTR" as opposed to "five_prime_UTR" or "three_prime_UTR", since there is nothing to be 5' or 3' to.

2) Do we need transcription start/stop as regions?   Are these returned as 'variant effect' type answers in (say) snpeff?

3) "exon" is potentially confusing, in that I think that its role here is to state that the coordinate is pointing at a coding region.  But the UTRs are also exonic.  Is there a more specific term that we could use?

**Comment by srynobio** [comment]
## _What the region type for a location in a non-coding transcript?_  

A couple of terms come to mind if you wanted to denote this:
1. [noncoding_exon](http://www.sequenceontology.org/browser/current_svn/term/SO:0000198)
2. [pseudogenic_transcript](http://www.sequenceontology.org/browser/current_svn/term/SO:0000516)

These regions would be different than a UTR region which is untranslated vs. non-coding.

## _Do we need transcription start/stop as regions_

I would have to believe that these are important region to annotate, and annotation tools would not return this as a effect, the return would be.

| Region | Effect |
| --- | --- |
| [TSS](http://www.sequenceontology.org/browser/current_svn/term/SO:0000315) | [start_lost](http://www.sequenceontology.org/browser/current_svn/term/SO:0002012) |
| [transcription_end_site](http://www.sequenceontology.org/browser/current_svn/term/SO:0000616) | [stop_lost](http://www.sequenceontology.org/browser/current_svn/term/SO:0001578) |

Of course the regions could be recorded as exon, using the same effect. Then the more descriptive region of TSS & TES could become ancillary. 

## _Is there a more specific term that we could use?_

Yes, as before we had coding_exon as the primary term, I ultimately made the change to exon as coding_exon is something I have yet to see in a GFF3 file.  Another option is CDS, but it describe quite a large region.

**Comment by cbizon** [comment]
1) Region type for non-coding transcript:  I think that "pseudogenic_transcript" is the best term for this.

2) transcription start/stop: I think I'd put these ancillary and handle via the effect

3) The problem with exon is that the UTR is also in exons.  The problem with coding_exon is that it relates to the exon.  So you can be in a "coding_exon" but not in the coding region of the coding_exon if the coding exon contains both UTR and CDS.   I think that CDS is the term that we want - it tells you that this allele is going to (potentially) affect the coding, which is what we really want to know.  What was the issue with CDS from your perspective?
