### ISSUE TITLE
JSON schema

### ISSUE THREAD

**Issue by ronakypatel** [tnavatar/clingen-data-model#52]
I see xsd is available for resources (http://clingen-data-model.github.io/main/resources/clingen-xsd/canonicalallele.xsd), is it possible to have JSON schema for resource models? Although it is not required and can be generated by user, I thought it would be useful.

**Comment by larrybabb** [comment]
Ronak, I've never created a json schema.  Would a tool like http://jsonschema.net/#/ be sufficient for developing this?

**Comment by ronakypatel** [comment]
Yes Larry, it should be possible.

I thought as the examples are available in JSON, you might have JSON schema for them. Here we use JSON, so I thought it would save some work for me.

**Comment by larrybabb** [comment]
Ronak, I did not mean for you to have to close this issue. If it helps for us to produce a json schema, then maybe as a result of some of the work that Chris Bizon is doing to produce a JSON-LD model we will be able to give you the end result in a json-schema asset.

I'll reopen this issue to make sure we follow through with the rest of the team on whether or not to produce the json-schema.

**Comment by cbizon** [comment]
It would be nice to have this for 0.1 but it is not high priority for Ronak
