### ISSUE TITLE
grouping and structure for examples

### ISSUE THREAD

**Issue by tnavatar** [tnavatar/clingen-data-model#53]
Larry had mentioned wanting to add a little structure to the examples we have. Could Larry (or anyone in the know) describe what type of organization we're looking for? I'm in the process of extracting some of the logic in our models into an extension to Middleman, and it would be helpful to know what to support by way of examples.

**Comment by larrybabb** [comment]
On the FHIR CI [Implementation](http://hl7-fhir.github.io/implementation.html) page they have a link to the start of an [Integrated Examples](http://hl7-fhir.github.io/integrated-examples.html) page. I was thinking we could do something like this, but I don't think it should be a strict requirement.

I was thinking we will want the current index-like listing still available somewhere on the site, maybe just not the first page in the Examples section.  In the end, I envision a page that has a list of "Scenarios" with a name and high-level description.  Each scenario would discuss the problem (related to canonicalizing variants in the real world) and solution (like a proof maybe - Problem, Given, Solution?). And there would possibly be links to clinvar or other external sites or hand written data elements in the problem and finally a solution that has embedded links to the examples (xml/json) that support it.  And maybe a list at the end of the scenario that provides all the related examples.

We will need to build up to this, but I really do think this is one of the more redeeming value points in our project.  If nothing else, it really clarifies with real, detailed information the issues that go unrecognized by the masses and the justification and need for variant canonicalization.

Related, but minor, point.  It may make sense to provide links directly in the examples for resource examples that reference other resource examples (i.e SimpleAllele-1 to ReferenceSequnce-5, 6, 7 as an idea).  These example-to-example links could be embedded directly in the examples or as a list at the bottom of each example.  It would be pretty handy when discussing to be able to navigate around the examples that way.  May help people make a stronger connection to the associations and resources that seem unrelated or less obvious.

**Comment by tnavatar** [comment]
OK, interesting. To me the integrated example sounds like it's structured like our free text markdown, assisted by some helper functions that can build the tables on that page given structured sample data. This feels pretty doable to me.

On a slightly related note, how are you generating the sample data now? Do you have it in some structured form that generates both the JSON and XML views?

**Comment by larrybabb** [comment]
No. I used eclipse and JAX-B to generate the baseline schemas for the resource objects, which I created manually (yuck).  And, then I manually tweaked the schemas to reflect the schemas produced by FHIR (you can download there schemas from the FHIR spec site).  Then I used the schema to create the samples manually (yuck, again).  Obviously, not scalable when the model changes. This is a fundamental reason why we may want to seriously consider piggy backing on the FHIR spec build process.  Then we would have only one place to make model updates, in general.  I am not sure whether the sample data would be generate-able in any case.
