### ISSUE TITLE
An JSON-LD Concept that may help us.

### ISSUE THREAD

**Issue by srynobio** [tnavatar/clingen-data-model#55]
I've been reading through the [JSON-LD](http://www.w3.org/TR/json-ld/) page today and @cbizon slides, and something that will help us is concept of [default-vocabulary](http://www.w3.org/TR/json-ld/#default-vocabulary).  

A first pass (in thought) would be that we create a new page which defines the "name:" we will use with links to the documentation page.

**Comment by cbizon** [comment]
I think that the @vocab is useful.   I haven't put it into the examples yet, because I figured it would be easy enough to add later.  Instead I used compact IRIs to designate families of terms (clingin, fhir).  I figure that at a later date, we can choose one of those to make the default and put it in as a vocab.

**Comment by ronakypatel** [comment]
@vocab is indeed useful. It might serve like local ontology. The @vocab#property when dereferenced describes the property. 

Say for example the Gene-Symbol at bio2rdf is defined as:
http://bio2rdf.org/hgnc_vocabulary:Gene-Symbol

Similarly, the accession is defined as
http://bio2rdf.org/hgnc_vocabulary:accession 

Please note that it is not JSON-LD but RDF.

**Comment by srynobio** [comment]
My thought for using @vocab is we can reduce the amount of supporting documents needed (ReferenceSequence.jsonld). then use @vocab in each example.

@ronakypatel @cbizon would it be used in the correct context this way?

```
{
    "@context": {
        "@vocab":"http://hl7.org/fhir/resources/",
        "@vocab":"http://clingen.org/model/allele/","
    },
  "@id": "http://clingendb.clingen.org/ReferenceSequence/RS201",
  "@type": "ReferenceSequence"
  "identifier": 
  [
    {
      "label": "Homo sapiens integrin-linked kinase (ILK), transcript variant 2, mRNA",
      "system": "http://www.ncbi.nlm.nih.gov/nuccore",
      "value": "NM_001014794.2"
    }
  ],
  "sequenceClass": "nucleotide",
  "nucleotideSequenceClass": "transcript",
  "cdsStart": "162",
  "cdsEnd": "1520",
  "gene": "../../Gene/G101"
}
```

I'm also willing to admit this may be a hackish way of doing it.

**Comment by srynobio** [comment]
I just jumped on the JSON-LD IRC and asked them about this method.  They agree it would be easier to create the document, but we would have a lost of understanding because of a "from which to where" issue.

Still good to know if we have small sections of vocab needed throughout.

**Comment by cbizon** [comment]
I'm not 100% certain, but I don't think that there can be two vocab directives operational at the same time. 

```
JSON-LD's @vocab keyword allows an author to set a common prefix to be used for all properties and types that do not match a term and are neither a compact IRI nor an absolute IRI 
```

So in other words if you have "label" which isn't explicitly defined in the context, but you do have something that says

```
"@vocab":""http://clingen.org/model/allele/"
```

Then "label" expands to "http://clingen.org/model/allele/label".

If you had 2 vocabs, it wouldn't know which one to expand to.  (I think it's last one wins.)

**Comment by srynobio** [comment]
Based on my talk on the IRC, I believe you're right.
