### ISSUE TITLE
SimpleAlleleRelationshipType?

### ISSUE THREAD

**Issue by cbizon** [tnavatar/clingen-data-model#58]
This exists in the resource model.  I assume that it's there to link a transcript allele to an amino acid allele.  Are the codes defined anywhere?

**Comment by srynobio** [comment]
In the model or docs?

**Comment by cbizon** [comment]
Either?

**Comment by larrybabb** [comment]
Its only in the example and schemas related to SimpleAllele.  Check out [SimpleAllele.xsd](https://github.com/tnavatar/clingen-data-model/blob/master/source/main/resources/clingen-xsd/simpleallele.xsd) you will see the list for the attribute towards the bottom.  

I totally made it up.  Two values [effect, cause].  I guessed that they could be used to define the relationship from a transcriptAllele to an aminoAcidAllele (effect) and for the opposite relationship (cause).

Totally up for discussion.  BTW - all my made up enumerations are in the [XSDs](https://github.com/tnavatar/clingen-data-model/tree/master/source/main/resources/clingen-xsd).

**Comment by larrybabb** [comment]
They have been updated

```
<xs:simpleType name="SimpleAlleleRelationshipType-list">
  <xs:restriction base="xs:string">
    <xs:enumeration value="amino-acid-effect" />
    <xs:enumeration value="transcript-allele-cause" />
  </xs:restriction>
</xs:simpleType>
```
