### ISSUE TITLE
Complete index for DMWG

### ISSUE THREAD

**Issue by tnavatar** [tnavatar/clingen-data-model#6]
I modified the directory structure a little bit to accommodate the fact that we will, someday, do more than just an allele model. Included in this is a page to describe the overall scope and purpose of the ClinGen data model. I've created a stub for this page which needs to be completed: (source/index.md)

**Comment by cbizon** [comment]
This is about writing some text for the top level documentataion landing page. What the group is, what the scope is, why we are doing this...

**Comment by cbizon** [comment]
Include sections on interesting discussions: 
- numbering
- FHIR / JSON-LD.

**Comment by cbizon** [comment]
And 
- Allowed allele names.

**Comment by cbizon** [comment]
This is complete, but I have not included the sections on numbering, JSON-LD, or allowed allele names.  Once I started looking, I decided that these were actually topics to be covered on the allele page.  I am adding a ticket to do that.
