### ISSUE TITLE
Reference coordinate numbering (Global Alliance, BED, UCSC approach)

### ISSUE THREAD

**Issue by larrybabb** [tnavatar/clingen-data-model#60]
This is worth considering, since our model is still very much in flux and open to strengthening.  Here's an email I received from Bob Millius (HL7 Clinical Genomics WG member and Senior Data Analyst from the National Marrow Donor Program.).  He reviewed our reference coordinate numbering documentation and choice and replied as follows:

From: Bob Milius bmilius@nmdp.org
Date: Tuesday, March 24, 2015 at 11:51 AM
To: "Babb, Larry J." lbabb@geneinsight.com, "Holt, Jonathan" jonathan.holt@Vanderbilt.Edu, Amnon Shabo amnon.shvo@gmail.com
Subject: Re: Clinical Genomics FHIR extension

Thanks Larry!

FYI, At NMDP, we’ve settled on a 0-based coordinate system with closed-open ranges, i.e., the range includes the start position, but excludes the end position. This convention is used in many genomic data models, e.g., Global Alliance for Genomics and Health schemas (readMethods in http://ga4gh.org/#/schemas) , internal representations of the UCSC browser (http://genome.ucsc.edu/FAQ/FAQtracks.html#tracks1), BED files (http://genome.ucsc.edu/FAQ/FAQformat.html#format1), and lends itself to programmability. The first position of a sequence is numbered 0. So a representation of the first nucleotide of a sequence would be start=0, end=1.

Bob

— 
Bob Milius, Ph.D.
Senior Data Analyst, Bioinformatics Research
National Marrow Donor Program
3001 Broadway Street N. E. Suite 100, Minneapolis, MN 55413-1753

Office: 612-627-5844 | Cell: 612-810-2892

**Comment by cbizon** [comment]
Yeah, this is something that Bradford and I have been chewing over.   His point was that if we switch our numbering from 1 to 0, while keeping the interval counting, then it becomes the same as the UCSC/bed approach, which has the benefit of us being able to say that we're not inventing something.

Even better, it has the advantage of making the intron numbering make a little more sense (in ways that I can explain at a later time.)

The disadvantage is that it means that when you get an HGVS you have to do some 1-shifting.  But, given that this is not the display format, I am forced to agree that going 0-based would make more sense.  

(I was supposed to post something here proposing this change, but I hadn't gotten to it yet...  thanks for jogging me with this)

**Comment by bpow** [comment]
From another relevant point, there are two prominant coordinate systems currently in use in bioinformatics, the 1-based that points to the characters themselves and the 0-based that point between the sequence characters. Making a third convention that is 1-based pointing between sequence characters would add a whole new potential range of off-by-one errors. One of the first comments I had to @cbizon was about this issue, and I would be happy to go with the 0-based-intervals format (like UCSC/bed/ga4gh).

There are few relevant [discussions](https://www.biostars.org/p/84686/) [on](https://www.biostars.org/p/6373/) biostars.org

**Comment by cbizon** [comment]
Sounds like we are all OK with going 0-based.  
1) Any objections?
2) Any volunteers for updating the documentation?

**Comment by larrybabb** [comment]
I'll take a stab at it.

From:  cbizon notifications@github.com
Reply-To:  tnavatar/clingen-data-model
<reply+000ea21b38e73002e501909cdbc194b18e6b4a712c15046092cf00000001112a75419
2a169ce03d19347@reply.github.com>
Date:  Wednesday, March 25, 2015 9:08 AM
To:  tnavatar/clingen-data-model clingen-data-model@noreply.github.com
Cc:  Lawrence Babb larry.babb@gmail.com
Subject:  Re: [clingen-data-model] Reference coordinate numbering (Global
Alliance, BED, UCSC approach) (#60)

Sounds like we are all OK with going 0-based.

1) Any objections?
2) Any volunteers for updating the documentation?

‹
Reply to this email directly or view it on GitHub
<https://github.com/tnavatar/clingen-data-model/issues/60#issuecomment-86016
760> .

**Comment by larrybabb** [comment]
Here's some more references to highlight the pros and cons of 0-based v 1-based coordinate systems from Bob Milius.

Don’t mean to belabor this, but I thought I'd share some other reading material regarding genomic coordinate systems. 
As you can see from the various discussions, different browsers (UCSC vs Ensembl) and different file formats (GFF, SAM  vs  BED, BAM) use different coordinate/number systems.

Question: What Are The Advantages/Disadvantages Of One-Based Vs. Zero-Based Genome Coordinate Systems
https://www.biostars.org/p/6373/

Tutorial: Cheat Sheet For One-Based Vs Zero-Based Coordinate Systems
https://www.biostars.org/p/84686/

Coordinate Transforms
http://genomewiki.ucsc.edu/index.php/Coordinate_Transforms

Genome Coordinate Conventions 
http://alternateallele.blogspot.com/2012/03/genome-coordinate-conventions.html

Genome Coordinate Cheat Sheet
http://alternateallele.blogspot.com/2012/03/genome-coordinate-cheat-sheet.html

Bob
— 
Bob Milius, Ph.D.
Senior Data Analyst, Bioinformatics Research
National Marrow Donor Program
3001 Broadway Street N. E. Suite 100, Minneapolis, MN 55413-1753

Office: 612-627-5844 | Cell: 612-810-2892

**Comment by cbizon** [comment]
Actually, I need to amend my comments a bit as for what I said on the phone today and bring up some different options that Bradford & I discussed.

So, take as given: interval counting, zero based.    The question is how to handle negative counting in an intron region.

Lets say we have something like

ACGTacACGT

the intron acgt is in the interval that would normally be numbered 4 in the transcript.

If we consider the acgt to be another sequence, then we can number it

0 a 1 c 2

or bringing in the surrounding exon, like this:

(3,0) T (4,0) a (4,1), c(4,2) A (5,0)

So far, so good.  But the problem comes up when we want to number from right to left as is done in HGVS.  There are a few options:

1) Start at -1:

(3,0) T (4,-3) a (4,-2) c (4,-1) A (5,0)

This would work, but it doesn't actually preserve the distance property of (end - start) = length.  For these cases, assume that we're deleting cA.  Then start = (4,-2), end = (5,0).  end - start = 
1 + 2 = 3, but the length is 2.   Also, it's somewhat inconsistent: we way we're zero based, but here's an exception.

2) Start at 0:

(3, 0)  T  (4,-2) a (4,-1) c (4,0) A (5,0)

Now, this does give us the distance property: start = (4,-1), end = (5,0), end - start = 1 + 1 = 2.  Also, it's more consistent, since zero-based is zero-based.

But: now the position (4,0) is ambiguous.  How do you define an insertion at (4,0) counting from the left vs (4,0) counting from the right?   The only way to do this is to include a flag on every intronCoordinate that says whether we're counting left or right.

3) Don't let anybody count from the right.   This is actually the right answer, but it is not practical, because we are going to get right counted HGVS expressions that we have to deal with, and if you are going to convert them into left counted, then you are going to have to know the length of the intron, and that's no information that is derivable from the HGVS expression itself.

4) (Crazy version)  When counting from the right use the next interval as the major value:

(3,0) T (5,-3) a (5,-2) c (5,-1) A (5,0)

Preserves the distance property, unambiguous numbering.  The only con is that it will drive people insane.

Opinions?

**Comment by larrybabb** [comment]
I spent a good bit of brain power trying to both verify your analysis as well as looking for alternatives. I am in full agreement and think that we should go with the extra "direction" attribute for intron offset coordinates since we are firm on the 0-based indexing.  I also think we should consider keeping all coordinates as positive integer values and relying on this additional direction attribute.  This way the direction attribute enumeration of either (+ or -) would be significant in all intron offset calculations not just when it is 0.

(3,0)    |             (4,0)                |     (5,0)      <--- transcript 0-based index
   |       T  !     a      !       c      !   A       |
(+)         (4,0) !    (4,1)   !   (4,2)                   <--- positive intron offset 0-based index
(-)          (4,2) !    (4,1)   !   (4,0)                   <--- negative intron offset 0-based index

**Comment by cbizon** [comment]
I agree with Larry on the best option for coding this.

**Comment by larrybabb** [comment]
As a result of this conversation, I have added a "convention" code to the ReferenceCoordinate that will allow the implementer to pass either "zero-based" or "one-based" to represent the coordinate numbering convention used in the data represented in a given instance.  That said, I think the AlleleRegistry project should store everything in zero-based format.  

I do believe we must provide the opportunity for other implementations to use the one-based approach.  That said, if they do we (I) will provide documentation on how the intronOffset numbering would play into the one-based coordinate numbering using info from the conversation above.

Please take a look at the updated additions to the "ReferenceCoordinate" in both conceptual and resource models to see the new CoordinateConvention code attribute.

Let me know if you have an issue. Otherwise we can close this out.

**Comment by cbizon** [comment]
I have an issue (sorry).  What do you mean by 1-based?  Do you mean 1 based intervals (which would be quite non-standard and nobody is asking for) or do you mean 1-based positions (which we would need to fully specify)?

Also, why do we want to allow this?  Why not provide what we think is best?  It's our job to make these kind of choices, I think.

**Comment by larrybabb** [comment]
1-based is positional and 0-based is spaces.  I specify this in the
documentation for the code values.  I was reading up on several of those
links that highlight these issues, and while this page
<http://alternateallele.blogspot.com/2012/03/genome-coordinate-conventions.h
tml>  breaks out 3 styles, the author then notes that 2 end up being quite
similar based on the reference table here
<http://alternateallele.blogspot.com/2012/03/genome-coordinate-cheat-sheet.h
tml> .  So, I boiled it down to 2 for simplicity.

I think we make recommendations, but do not limit the choices.  These
resource schemas  are structures to allow parties to communicate
representations of these concepts to and from each other.  When we work with
a group like the Allele Registry we can advocate for the use of 0-based but
we do not want to completely restrict.  If two groups want to deal with
1-based issues or transform between 1 and 0 based representations, what
issue is it of ours.  If one convention has more serious limitations it is
our job to point that out, not regulate it.

From:  cbizon notifications@github.com
Reply-To:  tnavatar/clingen-data-model
<reply+000ea21b859b7375059f01f39c9f52f0213116fc5bd4269692cf0000000111365db19
2a169ce03d19347@reply.github.com>
Date:  Friday, April 3, 2015 9:54 AM
To:  tnavatar/clingen-data-model clingen-data-model@noreply.github.com
Cc:  Lawrence Babb larry.babb@gmail.com
Subject:  Re: [clingen-data-model] Reference coordinate numbering (Global
Alliance, BED, UCSC approach) (#60)

I have an issue (sorry).  What do you mean by 1-based?  Do you mean 1 based
intervals (which would be quite non-standard and nobody is asking for) or do
you mean 1-based positions (which we would need to fully specify)?

Also, why do we want to allow this?  Why not provide what we think is best?
It's our job to make these kind of choices, I think.

‹
Reply to this email directly or view it on GitHub
<https://github.com/tnavatar/clingen-data-model/issues/60#issuecomment-89296
178> .

**Comment by larrybabb** [comment]
coordinateConvention codes (0/1-based) have been removed.  I will open a new issue for the documentation work on the numbering explanation rewrite.

Tristan - could you rebuild the project (the xml examples have been restored as well).
