### ISSUE TITLE
primary amino acid change type

### ISSUE THREAD

**Issue by cbizon** [tnavatar/clingen-data-model#63]
Starting here:

http://clingen-data-model.github.io/allele/implementation/value_set_list/primary_amino_acid_change_type.html

1) Not everything in this list is an AA change type.   A UTR variant does not change any amino acids, intronic doesn't change amino acids, intergenic, and so on.  This is only a field on AminoAcid alleles, so this list needs to be culled down a lot.

2) Once 1 is done, then it will be easier to answer the question of whether an ancillary AA change type is needed.

**Comment by srynobio** [comment]
_1) Not everything in this list is an AA change type. A UTR variant does not change any amino acids, intronic doesn't change amino acids, intergenic, and so on. This is only a field on AminoAcid alleles, so this list needs to be culled down a lot._
1. Variants in the 5 & 3' UTR while not translated can lead to modification, and regulatory alteration which can affect a protein of interest/disease.  
2. Changes in the intergenic region can also have protein altering effects, e.g. promoter regions.

One aspect needs clarification.  Often when changes are reported at the amino acid level, the physical and functional changes are interleaved, between different variants.  So you will/can see terms like frameshift_variant and 3_prime_UTR_variant being used.  If we were only strictly reporting amino acid changes you would expect to see things like UCA -> CCA. (Ser -> Pro) which would tell us very little about what is happening biologically.

Another thing which I must mention is that this list was the union of what the three major tools will report as protein alterations, with additional terms added from each which biologically and logically belong.  One term I've struggled with addding is [transcript_ablation](http://www.sequenceontology.org/miso/current_release/term/SO:0001893) which does make sense, but would require the top parent term being move one node up; it's used by a couple of the terms and ensembl uses it http://www.ensembl.org/info/genome/variation/predicted_data.html.

**Comment by cbizon** [comment]
The problem is that this is an attribute of a Simple Amino Acid Allele.  For what possible Simple Amino Acid Allele will you use the Amino Acid Change Type "intergenic"? 

Also, I don't understand your Ser-> Pro example.  

Thanks

**Comment by srynobio** [comment]
A couple of Pubmed results looking for examples:

http://www.ncbi.nlm.nih.gov/pubmed/25394790
http://www.sciencedirect.com/science/article/pii/S109727651400205

**Comment by cbizon** [comment]
I think we are talking at cross-purposes a little bit.  There is no doubt that a genomic variant not in a protein can affect the function of the protein.   But that has (I think) nothing to do with this class.  This class is for defining an allele in an amino acid sequence.  That is, I have a sequence, I go to a particular position range, and I describe the amino acids that are in that range.

Now, I want to put a type on that particular allele.  By definition, the location of the allele is within the sequence.   This type is (or should be) 100% computable, with no knowledge of the functional effect of the change.  Note that this term does not define the full functional effect on the protein, nor does it need to cover functional effects on the protein by alleles that are not simple amino acid alleles.  All of that stuff is handled in other locations.

**Comment by srynobio** [comment]
I understand your point here, but this is a difficult area as we want to stay within the bounds of the model, but we also want to consider how people often use terms associated with amino acid changes.  I think it's quite common for the "thing" you're talking about and the "effect" it has to be interleaved.  Perhaps this is another strength of adding the ancillary type here as well.

**Comment by larrybabb** [comment]
My $.02.
From my perspective and relatively novice understanding of ontologies, the difference between primaryXXX and ancillaryXXX attributes in our model is that we want to define "precisely" what the primaryXXX attribute represents and this attribute in itself is not modeled by the sequence ontology developers.  Whereas, the ancillaryXXX list is more of a freestyle association between our entity and the world defined by the sequence ontology authors.

If we were to make our schema an ontology, we would have to find a relationship and possibly create new groupings and nodes within an entirely separate branch currently not defined by the sequence ontology schema.  So, we are sort of trying to have it both ways, which I believe is what is probably making Shawn's and Chris's perspective challenging to reconcile.

Not super helpful, I know.  But maybe it will help separate the two types of attributes in terms of what there purpose is and why.

**Comment by srynobio** [comment]
Yes helpful.  Rethinking that the primary-type will use SO mainly as a method to use standardized terms, whereas ancillary terms will include space for additional terms used by ontology authors, biologist, bioinformatician, current software and clinicians is nice because it gives us a "two bird one stone" approach.

**Comment by srynobio** [comment]
I wanted to post this list as a first version of the changes(so far) so we can continue to discuss them before I take the time to create pages.  I've ordered them similar to where they are found in the ontology.

Not all of the terms need to be included but I think this is a good subset of the ontology to pick from, considering were typing the "what's effected", not the "resulting effect"  Also if I'm missing any concepts here let me know.

```
synonymous_variant
    stop_retained_variant
    start_retained_variant  

frameshift_variant
    frameshift_truncation
    frameshift_elongation

inframe_variant
    inframe_insertion
    inframe_deletion
        conservative_inframe_insertion
        disruptive_inframe_insertion
        conservative_inframe_deletion
        disruptive_inframe_deletion

    nonsynonymous_variant
        stop_lost
        stop_gained
        start_lost
        missense_variant
            conservative_missense_variant
            non_conservative_missense_variant

```

Pointing out descriptive but possibly redundant terms here:

```
coding_sequence_variant
    ? terminator_codon_variant
    ? initiator_codon_variant

## covered in synonymous nonsynonymous.
amino_acid_substitution
    conservative_amino_acid_substitution
    non_conservative_amino_acid_substitution
```

Also a list of term which would be removed, leaving the terms to be annotated elsewhere (region)

```
five_prime_UTR
three_prime_UTR
internal_UTR
exon_variant
intron_variant
splice (any type)
```

**Comment by cbizon** [comment]
This looks good.  My suggestion would be:

```
synonymous_variant
frameshift_truncation
frameshift_elongation
conservative_inframe_insertion
disruptive_inframe_insertion
conservative_inframe_deletion
disruptive_inframe_deletion
stop_lost
stop_gained
start_lost
missense_variant
```

**Comment by srynobio** [comment]
One thing I think might be needed is the the idea of a "start gain" currently SO only uses 5_prime_UTR_premature_start_codon_variant.

**Comment by cbizon** [comment]
"start gain" is an interesting one.  But I'm a little confused about where we could put it.  It wouldn't be a value for an attribute on an amino acid variant, and it's not really a region_type that we might put on a transcript variant....
