### ISSUE TITLE
Exclusive Primary Nucleotide Change Types

### ISSUE THREAD

**Issue by cbizon** [tnavatar/clingen-data-model#68]
Current: http://clingen-data-model.github.io/allele/implementation/value_set_list/primary_nucleotide_change_type.html

I would take out:
inversion
structural alteration
translocation
copy number variation

And is there are clear distinction between indel and substitution?  Is there any overlap between these concepts (like MNV)?

**Comment by srynobio** [comment]
I'll re-review these again, I don't know if 100% agree with all of them being removed.

**Comment by srynobio** [comment]
What I'm thinking:

```
keep = inversion
lose for now = structural alteration
keep = translocation
keep = copy number variation
```

I think all of the above alteration type can biologically happen when describing a simple allele within a given transcript region.

_And is there are clear distinction between indel and substitution? Is there any overlap between these concepts (like MNV)?_

indel is generally used to describe a continuous change were something like a MNV describe SNP within  the same haplo-region.

If the group thinks clarity will be added by expanding substitution to more descriptive parts, the change would be quick.

**Comment by cbizon** [comment]
Sorry for leaving this one open a while.

I guess my question would be: why would we keep inversion, translocation, CNV when the model explicitly does not allow any such alleles to be included?  Any use of them would by definition be incorrect in version 0.1.

indel / substitution: I'm trying to understand the difference between these two.  Can you explain when each would be used and how you would differentiate between them (it looks like in the previous response you described indel vs MNV, but I was just using MNV as an example, it's really indel v substitution that is important here).
