### ISSUE TITLE
assigner for identifier

### ISSUE THREAD

**Issue by ronakypatel** [tnavatar/clingen-data-model#70]
I am trying to generate model for gene resource. 

Although not in example, "assigner" is a entity/property of "identifier" (of resource "gene"). The assigner is an entity of resource Organization. The Organization itself is dependent upon three resources (http://www.hl7.org/implement/standards/fhir/organization.html#Organization). 

Is there a way to get a gene model with all the the dependencies till it encounters simple types like string, int, float? I mean terminal nodes?

Also let me know if "assigner" is called an entity?

**Comment by bpow** [comment]
I think FHIR actually stores a `Reference` to the `assigner` (in the schema, `assigner`'s type is `ResourceReference`). The documentation for Identifier describes `assigner` as "Organization that issued id (may be just text)", so maybe we can get away with having a textual description of the assigner and be compliant. I'm not sure exactly how the ability to express the `assigner` as text is codified/validated, so they may not have worked that out themselves yet...

Assigner is not a required field, so we could also say that we just won't support that, but it is such a useful concept, especially when there are multiple sources of e.g. transcript coordinates.

**Comment by bpow** [comment]
Deferring for now, since assigner is not a required part of the FHIR identifier.
