### ISSUE TITLE
current codeable concept 

### ISSUE THREAD

**Issue by ronakypatel** [tnavatar/clingen-data-model#71]
I didnot find value list for ReferenceSequence.referenceGenome, In the preliminary implementation I will go ahead with hg18, hg19 and hg38.

Please confirm other value list I selected here:
nucleotideChangeType: enum(insertion, indel, copy_number_variation, inversion, deletion, substitution, structural_alteration, translocation, UPD, variant_collection)
aminoAcidChangeType: enum(functional_variant, structural_variant)
primaryTranscriptRegionType and ancillaryTranscriptRegionType: enum(edited_transcript_feature, exon, anchor_binding_site, primary_transcript_region, mature_transcript_region, exon_region, ribonuclease_site)

The only issue after this for I need resolution is looping in simpleAllele.referenceCoordinate before I get gene, referencsequence and simpleallele rolling.

**Comment by srynobio** [comment]
Ronaky,

Just now I've updated the valueSets for all the primary and ancillary change-types.  Also I'm a little unclear where you got the current valueSets you have.

--Shawn

**Comment by cbizon** [comment]
Also, for referenceGenome, we've been using the GRCh terminology, not the hg terminology (see e.g. the various example Reference Sequence documents in examples-json.)  

So GRCh36, GRCh37, GRCh38 instead of hg18, hg19, hg38.

**Comment by cbizon** [comment]
Just to be complete, if you look in the examples-jsonld-nofhir, at something like the RS202 example, you'll see a node like this:

```
  "referenceGenome": 
  {
    "@type":"ReferenceGenome",
    "@id":"http://www.ncbi.nlm.nih.gov/assembly/2758",
    "name": "GRCh37"
  }
```

**Comment by ronakypatel** [comment]
@srynobio I hope u mean _NCBI36_, GRCh37 and GRCh38?
Thanks @cbizon it is useful.

**Comment by srynobio** [comment]
No I was referring to your "Types" @ronakypatel 
And after looking at it again I kind of see what you were doing, but primaryTranscriptRegionType and ancillaryTranscriptRegionType are two different types.

**Comment by ronakypatel** [comment]
Yes, primaryTranscriptRegionType and ancillaryTranscriptRegionType are two types
primaryTranscriptRegionType: enum(CDS,exon,intron,noncoding_exon,pseudogenic_exon,splice_site,five_prime_UTR,three_prime_UTR)
ancillaryTranscriptRegionType: enum(transcription_start_site, three_prime_cis_splice_site, interior_exon, promoter, cryptic_splice_site)

They are different. In the first post, I wrote it like they are same, but I was wrong. 

One more thing: 

I don't see primary and anciallrynucleotideChangeType in xsd schema for simple allele: http://clingen-data-model.github.io/main/resources/clingen-xsd/simpleallele.xsd

instead it has only nucleotideChangeType.

**Comment by srynobio** [comment]
Yes, their are some updates that need to take place.  I'm going to go through the docs and update all the mentions of type, and make a JSON-LD example as well.

**Comment by larrybabb** [comment]
We reviewed (walked thru) the need for the intronOffsetGenomicCoordinate looping reference on the ReferenceCoordinate class with Ronak and clarified that this was strictly in place for intronic simple alleles that are based on transcript reference sequence and therefore need a genomic sequence coordinate in order to provide an actual pointer to the intronic base pair(s) that are referenced and/or altered as part of the SimpleAllele's definition.  Only one level of nesting will ever occur and only for intronic alleles.  (based on our collective knowledge and understanding to date).

**Comment by larrybabb** [comment]
I think I fixed these this morning.  They should be checked in.

From:  Shawn Rynearson notifications@github.com
Reply-To:  tnavatar/clingen-data-model
<reply+000ea21b27288be9e9fb661d45cc62455c2d3fef1d4835b492cf000000011133e62d9
2a169ce03e81ca2@reply.github.com>
Date:  Wednesday, April 1, 2015 1:00 PM
To:  tnavatar/clingen-data-model clingen-data-model@noreply.github.com
Subject:  Re: [clingen-data-model] current codeable concept  (#71)

Yes, their are some updates that need to take place.  I'm going to go
through the docs and update all the mentions of type, and make a JSON-LD
example as well.

‹
Reply to this email directly or view it on GitHub
<https://github.com/tnavatar/clingen-data-model/issues/71#issuecomment-88545
534> .
