### ISSUE TITLE
Canonical allele schema

### ISSUE THREAD

**Issue by ronakypatel** [tnavatar/clingen-data-model#73]
I am unable to find xsd schema now. I used it to understand models. If it is moved, then someone has to point me to the location. 

Anything else that describes model as a whole should be good. Going through individual example to generate model is not feasible, as example only describes part of model.

**Comment by tnavatar** [comment]
Hi Ronak,

I restored the links to the schema, they should be visible from the example pages now. I had seen that the XML examples were gone, so I took them off the page.

—Tristan

**Comment by ronakypatel** [comment]
Got it.

It is perfectly good to remove xsd schema. However, in absence of that and not JSON schema, it is not possible to have idea of model.

Closing the issue as I got the schema.

**Comment by larrybabb** [comment]
Hey Tristan, I just noticed the xml examples were gone as well.  Did I do
that or did someone else?  If it was me, it was accidental.  Please let me
know if you did it.

From:  tnavatar notifications@github.com
Reply-To:  tnavatar/clingen-data-model
<reply+000ea21be3db29cd520af535ad24493598808558710e159192cf00000001113d40029
2a169ce04015219@reply.github.com>
Date:  Wednesday, April 8, 2015 3:14 PM
To:  tnavatar/clingen-data-model clingen-data-model@noreply.github.com
Subject:  Re: [clingen-data-model] Canonical allele schema (#73)

Hi Ronak,

I restored the links to the schema, they should be visible from the example
pages now. I had seen that the XML examples were gone, so I took them off
the page.

‹Tristan

> On Apr 8, 2015, at 2:56 PM, ronakypatel notifications@github.com wrote:
> 
> I am unable to find xsd schema now. I used it to understand models. If it is
> moved, then someone has to point me to the location.
> 
> Anything else that describes model as a whole should be good. Going through
> individual example to generate model is not feasible, as example only describes
> part of model.
> 
> ‹
> Reply to this email directly or view it on GitHub.

‹
Reply to this email directly or view it on GitHub
<https://github.com/tnavatar/clingen-data-model/issues/73#issuecomment-91008
136> .

**Comment by tnavatar** [comment]
I think you deleted them in this commit:

https://github.com/tnavatar/clingen-data-model/commit/a489db30fd900afc7b2f852be0b6cd9de843b358

I can bring them back, though perhaps you did some updating of them since the last time they were committed?

**Comment by larrybabb** [comment]
Your right. I'm undoing now.

From:  tnavatar notifications@github.com
Reply-To:  tnavatar/clingen-data-model
<reply+000ea21bda67346cbf4db2046def297fc7f8f9a6056edcb792cf00000001113d57589
2a169ce04015219@reply.github.com>
Date:  Wednesday, April 8, 2015 4:53 PM
To:  tnavatar/clingen-data-model clingen-data-model@noreply.github.com
Cc:  Lawrence Babb larry.babb@gmail.com
Subject:  Re: [clingen-data-model] Canonical allele schema (#73)

I think you deleted them in this commit:

https://github.com/tnavatar/clingen-data-model/commit/a489db30fd900afc7b2f85
2be0b6cd9de843b358

I can bring them back, though perhaps you did some updating of them since
the last time they were committed?

> On Apr 8, 2015, at 4:49 PM, larrybabb notifications@github.com wrote:
> 
> Hey Tristan, I just noticed the xml examples were gone as well. Did I do
> that or did someone else? If it was me, it was accidental. Please let me
> know if you did it.
> 
> From: tnavatar notifications@github.com
> Reply-To: tnavatar/clingen-data-model
> <reply+000ea21be3db29cd520af535ad24493598808558710e159192cf00000001113d40029
> 2a169ce04015219@reply.github.com>
> Date: Wednesday, April 8, 2015 3:14 PM
> To: tnavatar/clingen-data-model clingen-data-model@noreply.github.com
> Subject: Re: [clingen-data-model] Canonical allele schema (#73)
> 
> Hi Ronak,
> 
> I restored the links to the schema, they should be visible from the example
> pages now. I had seen that the XML examples were gone, so I took them off
> the page.
> 
> ‹Tristan
> 
> > On Apr 8, 2015, at 2:56 PM, ronakypatel notifications@github.com wrote:
> > 
> > I am unable to find xsd schema now. I used it to understand models. If it is
> > moved, then someone has to point me to the location.
> > 
> > Anything else that describes model as a whole should be good. Going through
> > individual example to generate model is not feasible, as example only
> > describes
> > part of model.
> > 
> > ‹
> > Reply to this email directly or view it on GitHub.
> 
> ‹
> Reply to this email directly or view it on GitHub
> <https://github.com/tnavatar/clingen-data-model/issues/73#issuecomment-91008
> 136> .
> 
> —
> Reply to this email directly or view it on GitHub.

—
Reply to this email directly or view it on GitHub
<https://github.com/tnavatar/clingen-data-model/issues/73#issuecomment-91034
113> .
