### ISSUE TITLE
Rewrite Coordinate numbering section

### ISSUE THREAD

**Issue by larrybabb** [tnavatar/clingen-data-model#74]
Create a separate "special topics" page on coordinate numbering to explain the requirement for 0-based interval numbering with linked examples, explanations and handling of special scenarios surrounding intronic transcript offset numbering.
provide link outs from both the conceptual and resource pages where appropriate.

**Comment by cbizon** [comment]
I believe I heard on the call yesterday that @srynobio  would take this one on, so I am assigning it to him.  If that is not right, feel free to change it back to unassigned.

**Comment by larrybabb** [comment]
For Larry
Rework the examples for 0-based.
Send to Chris
