### ISSUE TITLE
Consider allowing 0 or 1 based coordinates

### ISSUE THREAD

**Issue by cbizon** [tnavatar/clingen-data-model#75]
In allele 0.1, we use only 0-based coordinates.

Some users may like to use 1-based coordinates.  Some may simply assume that the model uses 1-based coordinates, thus leading to errors.

One option is to allow both 0 and 1 based coordinates in the model.

Pros:
- allows greater adoption
- fewer errors caused by assumption
- forces users to be explicit in numbering scheme

Cons: 
- Extra complexity without enhancing the breadth of the model
- Two numbering systems in the same model open a different class of errors

**Comment by srynobio** [comment]
I believe you're first pro is the strongest point for it.  Given that over the next few years (at least), >80% of the data coming in is going to be derived from VCF files, however if in both 0.1 and 0.2+ we're _very explicit_ about the coordinate system were using, maybe going so as to creating or directing people to tools that can do the conversion for them, adoption may be quicker.

As for the cons I also agree that using a two coordinate system will create a host of misinformation errors.
