### ISSUE TITLE
Discussion page for ClinVar integration/mapping

### ISSUE THREAD

**Issue by srynobio** [tnavatar/clingen-data-model#77]
I just wanted to post this before todays meeting.

I generated these lists by collecting terms and xrefs with the tag specified in the ClinVar Data Dictionary:

`Measure/AttributeSet/Attribute type=’MolecularConsequence’` 

First I wanted to see what terms they are using to compare them with what we've define in our model, however it's important to note that ClinVar allows _free text comment may be submitted_.

| Total Number | Term used |
| --- | --- |
| 358562 | missense variant |
| 156480 | intron variant |
| 98296 | synonymous variant |
| 56940 | frameshift variant |
| 46824 | non-coding transcript variant |
| 45357 | nonsense |
| 13344 | 2KB upstream variant |
| 9460 | splice donor variant |
| 9094 | 5 prime UTR variant |
| 7385 | splice acceptor variant |
| 7105 | 3 prime UTR variant |
| 6590 | inframe_variant |
| 3834 | Missense |
| 3636 | missense mutation |
| 3370 | 500B downstream variant |
| 1458 | synonymous mutation |
| 558 | frameshift mutation |
| 539 | stop lost |
| 534 | Nonsense |
| 372 | Splice Site acceptor |
| 360 | Splice Site donor |
| 264 | Silent |
| 26 | intergenic_variant |
| 22 | intron |
| 12 | Read-through mutation |
| 12 | no-stop change? |
| 12 | Frameshift |
| 6 | Splice Site |
| 6 | regulatory region ablation |
| 6 | exon_loss |
| 2 |  |
### Grouping by ID

Just as a quick first pass I decided to group terms used with SO id's offered, I randomlly picked SO:0001587 which in SO is defined here:

| SO term | SO ID |
| --- | --- |
| stop_gained | [SO:0001587](http://www.sequenceontology.org/browser/current_svn/term/SO:0001587) |

When you group terms to ID in ClinVar this is what I find:

| Total Number | Term used | ID used |
| --- | --- | --- |
| 38965 | _nonsense_ | SO:0001587 |
| 3203 | missense variant | SO:0001587 |
| 1052 | frameshift variant | SO:0001587 |
| 751 | intron variant | SO:0001587 |
| 504 | _Nonsense_ | SO:0001587 |
| 399 | non-coding transcript variant | SO:0001587 |
| 397 | synonymous variant | SO:0001587 |
| 163 | splice donor variant | SO:0001587 |
| 121 | 2KB upstream variant | SO:0001587 |
| 85 | splice acceptor variant | SO:0001587 |
| 84 | 5 prime UTR variant | SO:0001587 |
| 65 | 3 prime UTR variant | SO:0001587 |
| 61 | inframe_variant | SO:0001587 |
| 29 | 500B downstream variant | SO:0001587 |
| 18 | synonymous mutation | SO:0001587 |
| 18 | Missense | SO:0001587 |
| 12 | missense mutation | SO:0001587 |
| 6 | stop lost | SO:0001587 |
| 6 | frameshift mutation | SO:0001587 |

Thoughts?

**Comment by larrybabb** [comment]
add a subtopic on transforming Measureset ids to canonical and hgvs representations to simple allele.
