### ISSUE TITLE
Adding SO descriptions to the model

### ISSUE THREAD

**Issue by srynobio** [tnavatar/clingen-data-model#8]
I was wondering if adding the SO definition to the DM documentation is something that is needed?  If it is, i'll start adding it.

**Comment by tnavatar** [comment]
I see you closed this issue, and maybe it’s OK to just let it go. That said, this seems like an easy thing to do that has the potential to be helpful in understanding the model. Where there were SO terms in the description before I had moved them out into a separate metadata portion of the model objects (see reference_genome.md for an example). This means terms don’t show up in the display yet, but it makes it easy to add them later with appropriate links into the SO browser.

**Comment by srynobio** [comment]
I have checked in two pages which describe how the model will use the SO definitions, both changeType and regionType.  I still have the Gene element remaining.
