### ISSUE TITLE
SimpleAllele page needs updating.

### ISSUE THREAD

**Issue by srynobio** [tnavatar/clingen-data-model#86]
I noticed this about 8 paragraphs down, don't know if it in the process of being updated.

_[Move to canonical allele or somewhere higher up?] Though the main use of SimpleAllele is to record alleles at observed variant sites in the human genome, use of the SimpleAllele model does not demand that an instantiated allele actually be observed. Implementors may choose to use the model for different purposes; if a particular implementor demands that all entries to a database of SimpleAlleles represent observed variation, then it is incumbent upon that implementor to add documentation to that effect._

**Comment by tnavatar** [comment]
I noticed this too while working on the SimpleAllele resource. My thinking is that once we get the resource documentation in a good state, we'll be able to loop back and clean up the conceptual documentation.

**Comment by cbizon** [comment]
I tend to think that the statement is fine at the SimpleAllele level, and I would just remove the bracketed note, though others may feel differently.

Also, I thought that our current goal was to align the resource and conceptual docs / definitions.
