### ISSUE TITLE
Change the SO term for CanonicalAllele

### ISSUE THREAD

**Issue by srynobio** [tnavatar/clingen-data-model#87]
Currently we are using the following SO definition:
http://www.sequenceontology.org/browser/current_svn/term/SO:0001023

What do you think about this one:
http://www.sequenceontology.org/browser/current_svn/term/SO:0000993

**Comment by bpow** [comment]
Neither SO:0001023 or SO:0000993 fit exactly. SO:0001023 is close, but does not represent the "canonical" factor, and also has as part of its definition that the allele is described in terms of a gene (which means that it would not, for example, apply to intergenic GWAS SNPS. @srynobio will talk with SO folks about whether there is a more appropriate term or whether a more appropriate term could be added.
