### ISSUE TITLE
ReferenceSequence resource Notes

### ISSUE THREAD

**Issue by cbizon** [tnavatar/clingen-data-model#91]
says:
The preferred ReferenceSequence to bind an allele to will be the NC_\* reference assembly, as defined by RefSeq.
1. Is this saying that the data model defines the preferred names for an allele?  I thought that was up to the implementor?
2. What about amino acid sequences?

**Comment by tnavatar** [comment]
That one was my fault. Probably better to delete that statement altogether if you’re working on that page now.

**Comment by larrybabb** [comment]
I'm working on cleaning up ReferenceSequence right now. So, I can remove
that.

From:  tnavatar notifications@github.com
Reply-To:  tnavatar/clingen-data-model
<reply+000ea21b9fb9dfdcaa99787c4a5461840460a1617735cac392cf00000001114518ca9
2a169ce0414910e@reply.github.com>
Date:  Tuesday, April 14, 2015 2:04 PM
To:  tnavatar/clingen-data-model clingen-data-model@noreply.github.com
Subject:  Re: [clingen-data-model] ReferenceSequence resource Notes (#91)

That one was my fault. Probably better to delete that statement altogether
if you¹re working on that page now.

> On Apr 14, 2015, at 2:03 PM, cbizon notifications@github.com wrote:
> 
> says:
> The preferred ReferenceSequence to bind an allele to will be the NC_*
> reference assembly, as defined by RefSeq.
> 
>  Is this saying that the data model defines the preferred names for an
> allele? I thought that was up to the implementor?
> 
>  What about amino acid sequences?
> 
> 
> Reply to this email directly or view it on GitHub.


Reply to this email directly or view it on GitHub
<https://github.com/tnavatar/clingen-data-model/issues/91#issuecomment-93001
635> .

**Comment by tnavatar** [comment]
I’ll also do a pull-and-build before our call, for those of us (like me), working to get what we can done beforehand.
